--1. 은행(BANK) 테이블
CREATE TABLE BANK 
( BANK_ID  NUMBER
, BANK_NAME VARCHAR2(20) NOT NULL
, CONSTRAINT BANK_ID_PK PRIMARY KEY(BANK_ID)
);
--==>> Table BANK이(가) 생성되었습니다.

-- 은행 시퀀스 생성
CREATE SEQUENCE BANK_SEQ
NOCACHE;
--==>> Sequence BANK_SEQ이(가) 생성되었습니다.

--2. 공지사항 카테고리 (ANNOUNCE_CATEGORY) 테이블
CREATE TABLE ANNOUNCE_CATEGORY
( ANOUN_CATE_ID     NUMBER
, ANOUN_CATE_NAME   VARCHAR2(20) NOT NULL
, CONSTRAINT ANOUN_CATE_ID_PK PRIMARY KEY(ANOUN_CATE_ID)
);
--==>> Table ANNOUNCE_CATEGORY이(가) 생성되었습니다.

-- 공지사항 시퀀스 생성
CREATE SEQUENCE ANNOUNCE_CATEGORY_SEQ
NOCACHE;
--==>>Sequence ANNOUNCE_CATEGORY_SEQ이(가) 생성되었습니다.


--3. 문의 카테고리 ASK_CATEGORY 테이블
CREATE TABLE ASK_CATEGORY
( ASK_CATE_ID   NUMBER
, ASK_CATE_NAME VARCHAR2(20) NOT NULL
, CONSTRAINT ASK_CATE_ID_PK PRIMARY KEY(ASK_CATE_ID)
);
--==>> Table ASK_CATEGORY이(가) 생성되었습니다.

--문의 카테고리 시퀀스 생성
CREATE SEQUENCE ASK_CATEGORY_SEQ
NOCACHE;
--==>>Sequence ASK_CATEGORY_SEQ이(가) 생성되었습니다.

--4. FAQ 테이블 생성
CREATE TABLE FAQ
( FAQ_ID NUMBER
, FAQ_TITLE VARCHAR2(30) NOT NULL
, FAQ_CONTENTS VARCHAR2(300) NOT NULL
, CONSTRAINT FAQ_ID_PK PRIMARY KEY(FAQ_ID)
);
--==>> Table FAQ이(가) 생성되었습니다.

-- FAQ 시퀀스 생성
CREATE SEQUENCE FAQ_SEQ
NOCACHE;
--==>> Sequence FAQ_SEQ이(가) 생성되었습니다.







