/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-06-19 11:34:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class direct_005fplace_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1654491837648L));
    _jspx_dependants.put("jar:file:/C:/Final_Project_ComFIt/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comfit/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>구매제안</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .map_wrap {position:relative;width:100%;height:350px;}\r\n");
      out.write("    .title {font-weight:bold;display:block; font-size: 10px;}\r\n");
      out.write("    .hAddr {position:absolute;left:10px;top:10px; font-size: 10px; border-radius: 2px;background:#fff;background:rgba(255,255,255,0.8);z-index:1;padding:5px;}\r\n");
      out.write("    #centerAddr {display:block;margin-top:2px;font-weight: normal;}\r\n");
      out.write("    .bAddr {padding:5px;text-overflow: ellipsis;overflow: hidden;white-space: nowrap; font-size: 3px;}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\" integrity=\"sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\" integrity=\"sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css\" integrity=\"sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(function()\r\n");
      out.write("\t{\r\n");
      out.write("\t   var hope_sdate = $(\"#hope_sdate\").val();\r\n");
      out.write("\t   var hope_edate =\t$(\"#hope_edate\").val();\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t   var today = new Date();\r\n");
      out.write("\t   var sday = new Date(hope_sdate);\r\n");
      out.write("\t   \r\n");
      out.write("\t   var nowYear = today.getFullYear();\r\n");
      out.write("\t   var sYear = sday.getFullYear();\r\n");
      out.write("\t   \r\n");
      out.write("\t   var nowMonth = today.getFullMonth()+1;\r\n");
      out.write("\t   var sMonth = sday.getFullMonth()+1;\r\n");
      out.write("\t   \r\n");
      out.write("\t   var nowDay = today.getDate();\r\n");
      out.write("\t   var sDay = today.getDate();\r\n");
      out.write("\t   \r\n");
      out.write("\t   // 연도비교\r\n");
      out.write("\t   if (nowYear == sYear)\r\n");
      out.write("\t   {\r\n");
      out.write("\t\t\talert(\"연도같음, 월비교\");\r\n");
      out.write("\t\t\tif (nowMonth == sMonth)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"월 같음, 일비교\");\r\n");
      out.write("\t\t\t\tif (nowDay > sDay) // 오늘이 미래라면\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\thope_sdate = today;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(nowMonth > sMonth) // 지금월 이 미래라면\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\thope_sdate = today;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t   }\r\n");
      out.write("\t   else\r\n");
      out.write("\t   {\r\n");
      out.write("\t\t   alert(\"연도다름, 연도비교\");\r\n");
      out.write("\t\t   hope_sdate = today;\r\n");
      out.write("\t   }\r\n");
      out.write("\t \r\n");
      out.write("\t  \r\n");
      out.write("\t   $(\"#datePicker\").datepicker({\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   dateFormat: \"yy-mm-dd\" //데이터 포맷 형식(yyyy : 년 mm : 월 dd : 일 )\r\n");
      out.write("\t     , minDate: new Date(hope_sdate)\r\n");
      out.write("\t     , maxDate: new Date(hope_edate)\r\n");
      out.write("\t     , dayNamesMin: ['일', '월', '화', '수', '목', '금', '토']\r\n");
      out.write("\t     , monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월']\r\n");
      out.write("\t     , autoclose: true\r\n");
      out.write("\t     , onSelect: function() { \r\n");
      out.write("\t            var date = $.datepicker.formatDate(\"yymmdd\",$(\"#datePicker\").datepicker(\"getDate\")); \r\n");
      out.write("\t            date = $(\"#datePicker\").val();\r\n");
      out.write("\t     }\r\n");
      out.write("\t   })\r\n");
      out.write("\t   \r\n");
      out.write("\t   \r\n");
      out.write("\t});\r\n");
      out.write("   \r\n");
      out.write("   function suggest()\r\n");
      out.write("   {\r\n");
      out.write("\t\tvar suggest_price = document.getElementById(\"price\").value;\r\n");
      out.write("\t\tvar suggest_place = document.getElementById(\"suggest_place\").value;\r\n");
      out.write("\t\tvar place_detail = document.getElementById(\"place_detail\").value;\r\n");
      out.write("\t\tvar suggest_date = document.getElementById(\"datePicker\").value;\r\n");
      out.write("\t\tvar suggest_time = \"\"\r\n");
      out.write("\t\tvar hour = document.getElementById(\"suggest_hour\").value;\r\n");
      out.write("\t\tvar minute = document.getElementById(\"suggest_minute\").value;\r\n");
      out.write("\t\tif (minute<10)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tminute = \"0\"+minute;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsuggest_time = hour+\":\"+minute+\":00\";\r\n");
      out.write("\t\tvar u_id = document.getElementById(\"suggestion\").value;\r\n");
      out.write("\t\tvar pd_id = document.getElementById(\"pd_id\").value;\r\n");
      out.write("\t\tvar url = \"suggest_price=\" + suggest_price + \"&suggest_place=\" + suggest_place\r\n");
      out.write("\t\t\t\t+ \"&place_detail=\" + place_detail + \"&suggest_date=\" + suggest_date + \"&suggest_time=\" + suggest_time\r\n");
      out.write("\t\t\t\t+ \"&u_id=\"+u_id + \"&pd_id=\" +pd_id;\r\n");
      out.write("\t\tlocation.href = \"suggest.action?\"+url;\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" id=\"hope_sdate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hope_sdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" id=\"hope_edate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hope_edate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" id=\"pd_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pd_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"map_wrap\" style=\"margin-left: 1.5%; margin-top: 1.5%\">\r\n");
      out.write("    <div id=\"map\" style=\"width:500px;height:500px;position:relative;overflow:hidden;\"></div>\r\n");
      out.write("    <div class=\"hAddr\" >\r\n");
      out.write("        <span class=\"title\">지도중심기준 행정동 주소정보</span>\r\n");
      out.write("        <span id=\"centerAddr\"></span>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    <br />\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("\t<div style=\"margin-top: 30%\">\r\n");
      out.write("\t   <table class=\"table table-borderless\" style=\"width: 500px;\">\r\n");
      out.write("  \t\t\t<tr>\r\n");
      out.write("  \t\t\t\t<th>\r\n");
      out.write("  \t\t\t\t\t<label for=\"addr1\">희망장소</label>\t\t\r\n");
      out.write("  \t\t\t\t</th>\r\n");
      out.write("  \t\t\t\t<td colspan=\"2\">\r\n");
      out.write("  \t\t\t\t\t<input type=\"text\"  class=\"form-control\" name=\"hope_place\" id=\"suggest_place\" placeholder=\"지도에서 클릭해주세요\" readonly=\"readonly\"\r\n");
      out.write("  \t\t\t\t\t style=\"width: 300px; height: 35px; text-align: center;\" />\t\t\r\n");
      out.write("  \t\t\t\t</td>\r\n");
      out.write("  \t\t\t</tr>\r\n");
      out.write("  \t\t\t<tr>\r\n");
      out.write("  \t\t\t\t<th>\r\n");
      out.write("  \t\t\t\t     <label for=\"addr2\">장소상세</label>\r\n");
      out.write("  \t\t\t\t</th>\r\n");
      out.write("  \t\t\t\t<td colspan=\"2\">\r\n");
      out.write("  \t\t\t\t     <input type=\"text\" class=\"form-control\" name=\"place_detail\" id=\"place_detail\" style=\"width: 300px; height: 35px;\"/>\r\n");
      out.write("  \t\t\t\t</td>\r\n");
      out.write("  \t\t\t</tr>\r\n");
      out.write("  \t\t\t<tr>\r\n");
      out.write("  \t\t\t\t<th>\r\n");
      out.write("  \t\t\t\t\t<label for=\"hope_date\">거래희망날짜</label>\r\n");
      out.write("  \t\t\t\t</th>\r\n");
      out.write("  \t\t\t\t<td colspan=\"2\">\r\n");
      out.write("  \t\t\t\t\t<input  id=\"datePicker\" class=\"form-control\" placeholder=\"날짜를선택해주세요\" name=\"suggest_date\" \r\n");
      out.write("  \t\t\t\t\t style=\"width: 300px; height: 35px; text-align: center;\"/>\r\n");
      out.write("  \t\t\t\t</td>\r\n");
      out.write("  \t\t\t</tr>\r\n");
      out.write("  \t\t\t<tr>\r\n");
      out.write("  \t\t\t\t<th>\r\n");
      out.write("\t\t\t\t      <label for=\"hope_time\">거래희망시간</label>\r\n");
      out.write("  \t\t\t\t</th>\r\n");
      out.write("  \t\t\t\t<td>\r\n");
      out.write("  \t\t\t\t     <select class=\"form-select  form-select-sm\" aria-label=\"Default select example\" id=\"suggest_hour\"\r\n");
      out.write("  \t\t\t\t      style=\"width: 150px; height: 35px; text-align: center;\">\r\n");
      out.write("  \t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \t\t\t\t\t</select>\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t</td>\r\n");
      out.write("  \t\t\t\t<td>\r\n");
      out.write("  \t\t\t\t      <select class=\"form-select  form-select-sm\" aria-label=\"Default select example\" id=\"suggest_minute\"\r\n");
      out.write("  \t\t\t\t       style=\"width: 150px; height: 35px; text-align: center;\">\r\n");
      out.write("  \t\t\t\t      ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("  \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("  \t\t\t\t</td>\r\n");
      out.write("  \t\t\t</tr>\r\n");
      out.write("  \t\t\t<tr>\r\n");
      out.write("  \t\t\t\t<th>\r\n");
      out.write("  \t\t\t\t\t <label for=\"hope_price\">제안금액</label>\r\n");
      out.write("  \t\t\t\t</th>\r\n");
      out.write("  \t\t\t\t<td colspan=\"2\">\r\n");
      out.write(" \t\t\t\t      <input type=\"text\" class=\"form-control\" id=\"price\" style=\"width: 300px; height: 35px;\" />\r\n");
      out.write("  \t\t\t\t</td>\r\n");
      out.write("  \t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("        <button type=\"button\" id=\"suggestion\" class=\"btn-primary\" style=\"width: 150px; height: 35px; margin-left: 20%;\"\r\n");
      out.write("        \tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onclick=\"suggest()\">제안하기</button>\r\n");
      out.write("       <button type=\"reset\" class=\"btn btn-secondary\" style=\"width: 150px; height: 35px;\">취소</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=86ec7935feee50bc358cd41148ffd4e2&libraries=services\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t// 해당상품의 위도\r\n");
      out.write("   var lat = document.getElementById(\"lat\").value;\r\n");
      out.write("   //alert(lat);\r\n");
      out.write("   \r\n");
      out.write("   // 해당상품의 경도\r\n");
      out.write("   var lon = document.getElementById(\"lon\").value;\r\n");
      out.write("   //alert(lon);\r\n");
      out.write("   \r\n");
      out.write("   var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("       mapOption = {\r\n");
      out.write("           center: new kakao.maps.LatLng(lat,+lon), // 지도의 중심좌표 (게시물마다 중심 좌표가 될 값)\r\n");
      out.write("           level: 6 // 지도의 확대 레벨\r\n");
      out.write("       };  \r\n");
      out.write("   \r\n");
      out.write("   // 지도를 생성합니다    \r\n");
      out.write("   var map = new kakao.maps.Map(mapContainer, mapOption);\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 주소-좌표 변환 객체를 생성합니다\r\n");
      out.write("   var geocoder = new kakao.maps.services.Geocoder();\r\n");
      out.write("   \r\n");
      out.write("   var marker = new kakao.maps.Marker(), // 클릭한 위치를 표시할 마커입니다\r\n");
      out.write("       infowindow = new kakao.maps.InfoWindow({zindex:1}); // 클릭한 위치에 대한 주소를 표시할 인포윈도우입니다\r\n");
      out.write("   \r\n");
      out.write("   // 현재 지도 중심좌표로 주소를 검색해서 지도 좌측 상단에 표시합니다\r\n");
      out.write("   searchAddrFromCoords(map.getCenter(), displayCenterInfo);\r\n");
      out.write("   \r\n");
      out.write("   // 지도를 클릭했을 때 클릭 위치 좌표에 대한 주소정보를 표시하도록 이벤트를 등록합니다\r\n");
      out.write("   kakao.maps.event.addListener(map, 'click', function(mouseEvent) {\r\n");
      out.write("       searchDetailAddrFromCoords(mouseEvent.latLng, function(result, status) {\r\n");
      out.write("           if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("               var detailAddr = !!result[0].road_address ? '<div>도로명주소 : ' + result[0].road_address.address_name + '</div>' : '';\r\n");
      out.write("               detailAddr += '<div>지번 주소 : ' + result[0].address.address_name + '</div>';\r\n");
      out.write("               \r\n");
      out.write("               var content = '<div class=\"bAddr\">' +\r\n");
      out.write("                               '<span class=\"title\">법정동 주소정보</span>' + \r\n");
      out.write("                               detailAddr + \r\n");
      out.write("                           '</div>';\r\n");
      out.write("   \r\n");
      out.write("               // 마커를 클릭한 위치에 표시합니다 \r\n");
      out.write("               marker.setPosition(mouseEvent.latLng);\r\n");
      out.write("               marker.setMap(map);\r\n");
      out.write("   \r\n");
      out.write("               // 인포윈도우에 클릭한 위치에 대한 법정동 상세 주소정보를 표시합니다\r\n");
      out.write("               infowindow.setContent(content);\r\n");
      out.write("               infowindow.open(map, marker);\r\n");
      out.write("               \r\n");
      out.write("               document.getElementById(\"suggest_place\").value = result[0].address.address_name;\r\n");
      out.write("               \r\n");
      out.write("           }   \r\n");
      out.write("       });\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   // 중심 좌표나 확대 수준이 변경됐을 때 지도 중심 좌표에 대한 주소 정보를 표시하도록 이벤트를 등록합니다\r\n");
      out.write("   kakao.maps.event.addListener(map, 'idle', function() {\r\n");
      out.write("       searchAddrFromCoords(map.getCenter(), displayCenterInfo);\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   function searchAddrFromCoords(coords, callback) {\r\n");
      out.write("       // 좌표로 행정동 주소 정보를 요청합니다\r\n");
      out.write("       geocoder.coord2RegionCode(coords.getLng(), coords.getLat(), callback);         \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function searchDetailAddrFromCoords(coords, callback) {\r\n");
      out.write("       // 좌표로 법정동 상세 주소 정보를 요청합니다\r\n");
      out.write("       geocoder.coord2Address(coords.getLng(), coords.getLat(), callback);\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   // 지도 좌측상단에 지도 중심좌표에 대한 주소정보를 표출하는 함수입니다\r\n");
      out.write("   function displayCenterInfo(result, status) {\r\n");
      out.write("       if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("           var infoDiv = document.getElementById('centerAddr');\r\n");
      out.write("   \r\n");
      out.write("           for(var i = 0; i < result.length; i++) {\r\n");
      out.write("               // 행정동의 region_type 값은 'H' 이므로\r\n");
      out.write("               if (result[i].region_type === 'H') {\r\n");
      out.write("                   infoDiv.innerHTML = result[i].address_name;\r\n");
      out.write("                   break;\r\n");
      out.write("               }\r\n");
      out.write("           }\r\n");
      out.write("       }    \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function setDraggable(draggable) {\r\n");
      out.write("       // 마우스 드래그로 지도 이동 가능여부를 설정합니다\r\n");
      out.write("       map.setDraggable(draggable);    \r\n");
      out.write("   } \r\n");
      out.write("   \r\n");
      out.write("   map.setMaxLevel(6);\r\n");
      out.write("   setDraggable(false);\r\n");
      out.write("      \r\n");
      out.write("   var zoomControl = new kakao.maps.ZoomControl();\r\n");
      out.write("   map.addControl(zoomControl, kakao.maps.ControlPosition.RIGHT);\r\n");
      out.write("\r\n");
      out.write("   // 지도가 확대 또는 축소되면 마지막 파라미터로 넘어온 함수를 호출하도록 이벤트를 등록합니다\r\n");
      out.write("   kakao.maps.event.addListener(map, 'zoom_changed', function() {        \r\n");
      out.write("       \r\n");
      out.write("      if (map.getLevel()=='6')                                // 지도의 맥스 레벨이 6레벨이 되면 \r\n");
      out.write("         map.setCenter(new kakao.maps.LatLng(lat,+lon)); // 지도의 중심좌표 (게시물마다 중심 좌표가 될 값) 로 다시 이동\r\n");
      out.write("      \r\n");
      out.write("      if (map.getLevel()<='3') // 지도 레벨이 4이하 (구체적 건물표현정도)\r\n");
      out.write("         setDraggable(true);   // 로 떨어지면 드래그로 지도 위치를 바꿀수 있음\r\n");
      out.write("      else \r\n");
      out.write("         setDraggable(false);\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/user/main/direct_place.jsp(114,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("mgrs");
      // /WEB-INF/view/user/main/direct_place.jsp(114,1) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mgrs }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t<input type=\"hidden\" id=\"lat\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mgrs.lat }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("\t<input type=\"hidden\" id=\"lon\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mgrs.lon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/view/user/main/direct_place.jsp(170,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("time");
      // /WEB-INF/view/user/main/direct_place.jsp(170,8) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stime }", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/view/user/main/direct_place.jsp(170,8) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${etime }", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/view/user/main/direct_place.jsp(170,8) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setStep(1);
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("  \t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"font-size: 12pt;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("시</option>\r\n");
            out.write("  \t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/view/user/main/direct_place.jsp(179,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("minute");
      // /WEB-INF/view/user/main/direct_place.jsp(179,12) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setBegin(0);
      // /WEB-INF/view/user/main/direct_place.jsp(179,12) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setEnd(59);
      // /WEB-INF/view/user/main/direct_place.jsp(179,12) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setStep(10);
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("  \t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${minute }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"font-size: 12pt;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${minute }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("분</option>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
