/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-06-19 03:55:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class non_005fuser_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1654491837648L));
    _jspx_dependants.put("jar:file:/C:/Final_Project_ComFIt/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comfit/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메인화면</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\" />\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("   /* div {border: 1px solid black;} */\r\n");
      out.write("   .MultiCarousel { float: left; overflow: hidden; padding: 15px; width: 100%; position:relative; }\r\n");
      out.write("    .MultiCarousel .MultiCarousel-inner { transition: 1s ease all; float: left; }\r\n");
      out.write("    .MultiCarousel .MultiCarousel-inner .item { float: left;}\r\n");
      out.write("    .MultiCarousel .MultiCarousel-inner .item > div { text-align: center; padding:10px; margin:10px; background:#f1f1f1; color:#666;}\r\n");
      out.write("    .MultiCarousel .leftLst, .MultiCarousel .rightLst { position:absolute; border-radius:50%;top:calc(50% - 20px); }\r\n");
      out.write("    .MultiCarousel .leftLst { left:0; }\r\n");
      out.write("    .MultiCarousel .rightLst { right:0; }\r\n");
      out.write("    \r\n");
      out.write("    .MultiCarousel .leftLst.over, .MultiCarousel .rightLst.over { pointer-events: none; background:#ccc; }\r\n");
      out.write("   \r\n");
      out.write("   .newList > div.card \r\n");
      out.write("   {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      /* float: left; */\r\n");
      out.write("      margin: 10px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .lead\r\n");
      out.write("   {\r\n");
      out.write("      margin-top: 8px; margin-bottom: 8px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .card\r\n");
      out.write("   {\r\n");
      out.write("\t\twidth: 14rem;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .MultiCarousel .MultiCarousel-inner .item .pad15:hover\r\n");
      out.write("   {\r\n");
      out.write("   \t\tbackground-color: #A9D0F5;\r\n");
      out.write("   \t\tcursor:pointer;\r\n");
      out.write("   }\r\n");
      out.write("   .MultiCarousel .MultiCarousel-inner .item .pad15:active\r\n");
      out.write("   {\r\n");
      out.write("   \t\tbackground-color: #CEECF5;\r\n");
      out.write("   \t\tcursor:pointer;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("/* 메인 건드린 부분 */\r\n");
      out.write(" .box {\r\n");
      out.write("\t width: 1920px;\r\n");
      out.write("\t height: 400px;\r\n");
      out.write("\t border-radius: 0px;\r\n");
      out.write("\t box-shadow: ;\r\n");
      out.write("\t background: ;\r\n");
      out.write("\t position: relative;\r\n");
      out.write("\t overflow: ;\r\n");
      out.write("\t transform: translate3d(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write(" .wave {\r\n");
      out.write("\t opacity: 0.4;\r\n");
      out.write("\t position: absolute;\r\n");
      out.write("\t top: 3%;\r\n");
      out.write("\t left: 50%;\r\n");
      out.write("\t background: #0af;\r\n");
      out.write("\t width: 2000px;\r\n");
      out.write("\t height: 1920px;\r\n");
      out.write("\t margin-left: -250px;\r\n");
      out.write("\t margin-top: -250px;\r\n");
      out.write("\t transform-origin: 50% 48%;\r\n");
      out.write("\t border-radius: 43%;\r\n");
      out.write("\t animation: drift 3000ms infinite linear;\r\n");
      out.write("}\r\n");
      out.write(" .wave.-three {\r\n");
      out.write("\t animation: drift 5000ms infinite linear;\r\n");
      out.write("}\r\n");
      out.write(" .wave.-two {\r\n");
      out.write("\t animation: drift 7000ms infinite linear;\r\n");
      out.write("\t opacity: 0.3;\r\n");
      out.write("\t background: cyan;\r\n");
      out.write("}\r\n");
      out.write(" .box:after {\r\n");
      out.write("\t content: '';\r\n");
      out.write("\t display: block;\r\n");
      out.write("\t left: 0;\r\n");
      out.write("\t top: 0;\r\n");
      out.write("\t width: 100%;\r\n");
      out.write("\t height: 100%;\r\n");
      out.write("\t background: ;\r\n");
      out.write("\t z-index: 11;\r\n");
      out.write("\t transform: translate3d(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write(" .title {\r\n");
      out.write("\t position: absolute;\r\n");
      out.write("\t left: 0;\r\n");
      out.write("\t top: 0;\r\n");
      out.write("\t width: 100%;\r\n");
      out.write("\t z-index: 1;\r\n");
      out.write("\t line-height: 150px;\r\n");
      out.write("\t text-align: center;\r\n");
      out.write("\t transform: translate3d(0, 0, 0);\r\n");
      out.write("\t color: white;\r\n");
      out.write("\t text-transform: uppercase;\r\n");
      out.write("\t font-family: 'Playfair Display', serif;\r\n");
      out.write("\t letter-spacing: 0.4em;\r\n");
      out.write("\t font-size: 24px;\r\n");
      out.write("\t text-shadow: 0 1px 0 rgba(0, 0, 0, .1);\r\n");
      out.write("\t text-indent: 0.3em;\r\n");
      out.write("}\r\n");
      out.write(" @keyframes drift {\r\n");
      out.write("\t from {\r\n");
      out.write("\t\t transform: rotate(0deg);\r\n");
      out.write("\t}\r\n");
      out.write("\t from {\r\n");
      out.write("\t\t transform: rotate(360deg);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  min-width:px;\r\n");
      out.write("  white-space: nowrap;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  color: white;\r\n");
      out.write("  top:50%;\r\n");
      out.write("  left:50%;\r\n");
      out.write("  transform: translate(-50%, -50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3::before {\r\n");
      out.write("  content: \"지금 나에게 딱!! 맞는 컴퓨터\";\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  color: black;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  border-right: 1px solid black;\r\n");
      out.write("  animation: typing 5s steps(31) infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes typing{\r\n");
      out.write("  0% {\r\n");
      out.write("    width: 0%;\r\n");
      out.write("  }\r\n");
      out.write("  50% {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("  }\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("   $(document).ready(function () \r\n");
      out.write("   {\r\n");
      out.write("\t   \r\n");
      out.write("       var itemsMainDiv = ('.MultiCarousel');\r\n");
      out.write("       var itemsDiv = ('.MultiCarousel-inner');\r\n");
      out.write("       var itemWidth = \"\";\r\n");
      out.write("   \r\n");
      out.write("       $('.leftLst, .rightLst').click(function () {\r\n");
      out.write("           var condition = $(this).hasClass(\"leftLst\");\r\n");
      out.write("           if (condition)\r\n");
      out.write("               click(0, this);\r\n");
      out.write("           else\r\n");
      out.write("               click(1, this)\r\n");
      out.write("       });\r\n");
      out.write("   \r\n");
      out.write("       ResCarouselSize();\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("       $(window).resize(function () {\r\n");
      out.write("           ResCarouselSize();\r\n");
      out.write("       });\r\n");
      out.write("   \r\n");
      out.write("       //this function define the size of the items\r\n");
      out.write("       function ResCarouselSize() {\r\n");
      out.write("           var incno = 0;\r\n");
      out.write("           var dataItems = (\"data-items\");\r\n");
      out.write("           var itemClass = ('.item');\r\n");
      out.write("           var id = 0;\r\n");
      out.write("           var btnParentSb = '';\r\n");
      out.write("           var itemsSplit = '';\r\n");
      out.write("           var sampwidth = $(itemsMainDiv).width();\r\n");
      out.write("           var bodyWidth = $('body').width();\r\n");
      out.write("           $(itemsDiv).each(function () {\r\n");
      out.write("               id = id + 1;\r\n");
      out.write("               var itemNumbers = $(this).find(itemClass).length;\r\n");
      out.write("               btnParentSb = $(this).parent().attr(dataItems);\r\n");
      out.write("               itemsSplit = btnParentSb.split(',');\r\n");
      out.write("               $(this).parent().attr(\"id\", \"MultiCarousel\" + id);\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("               if (bodyWidth >= 1200) {\r\n");
      out.write("                   incno = itemsSplit[3];\r\n");
      out.write("                   itemWidth = sampwidth / incno;\r\n");
      out.write("               }\r\n");
      out.write("               else if (bodyWidth >= 992) {\r\n");
      out.write("                   incno = itemsSplit[2];\r\n");
      out.write("                   itemWidth = sampwidth / incno;\r\n");
      out.write("               }\r\n");
      out.write("               else if (bodyWidth >= 768) {\r\n");
      out.write("                   incno = itemsSplit[1];\r\n");
      out.write("                   itemWidth = sampwidth / incno;\r\n");
      out.write("               }\r\n");
      out.write("               else {\r\n");
      out.write("                   incno = itemsSplit[0];\r\n");
      out.write("                   itemWidth = sampwidth / incno;\r\n");
      out.write("               }\r\n");
      out.write("               $(this).css({ 'transform': 'translateX(0px)', 'width': itemWidth * itemNumbers });\r\n");
      out.write("               $(this).find(itemClass).each(function () {\r\n");
      out.write("                   $(this).outerWidth(itemWidth);\r\n");
      out.write("               });\r\n");
      out.write("   \r\n");
      out.write("               $(\".leftLst\").addClass(\"over\");\r\n");
      out.write("               $(\".rightLst\").removeClass(\"over\");\r\n");
      out.write("   \r\n");
      out.write("           });\r\n");
      out.write("       }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("       //this function used to move the items\r\n");
      out.write("       function ResCarousel(e, el, s) {\r\n");
      out.write("           var leftBtn = ('.leftLst');\r\n");
      out.write("           var rightBtn = ('.rightLst');\r\n");
      out.write("           var translateXval = '';\r\n");
      out.write("           var divStyle = $(el + ' ' + itemsDiv).css('transform');\r\n");
      out.write("           var values = divStyle.match(/-?[\\d\\.]+/g);\r\n");
      out.write("           var xds = Math.abs(values[4]);\r\n");
      out.write("           if (e == 0) {\r\n");
      out.write("               translateXval = parseInt(xds) - parseInt(itemWidth * s);\r\n");
      out.write("               $(el + ' ' + rightBtn).removeClass(\"over\");\r\n");
      out.write("   \r\n");
      out.write("               if (translateXval <= itemWidth / 2) {\r\n");
      out.write("                   translateXval = 0;\r\n");
      out.write("                   $(el + ' ' + leftBtn).addClass(\"over\");\r\n");
      out.write("               }\r\n");
      out.write("           }\r\n");
      out.write("           else if (e == 1) {\r\n");
      out.write("               var itemsCondition = $(el).find(itemsDiv).width() - $(el).width();\r\n");
      out.write("               translateXval = parseInt(xds) + parseInt(itemWidth * s);\r\n");
      out.write("               $(el + ' ' + leftBtn).removeClass(\"over\");\r\n");
      out.write("   \r\n");
      out.write("               if (translateXval >= itemsCondition - itemWidth / 2) {\r\n");
      out.write("                   translateXval = itemsCondition;\r\n");
      out.write("                   $(el + ' ' + rightBtn).addClass(\"over\");\r\n");
      out.write("               }\r\n");
      out.write("           }\r\n");
      out.write("           $(el + ' ' + itemsDiv).css('transform', 'translateX(' + -translateXval + 'px)');\r\n");
      out.write("       }\r\n");
      out.write("   \r\n");
      out.write("       //It is used to get some elements from btn\r\n");
      out.write("       function click(ell, ee) {\r\n");
      out.write("           var Parent = \"#\" + $(ee).parent().attr(\"id\");\r\n");
      out.write("           var slide = $(Parent).attr(\"data-slide\");\r\n");
      out.write("           ResCarousel(ell, Parent, slide);\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   $(document).ready(function()\r\n");
      out.write("   {\r\n");
      out.write("      $(\".hover\").hover(function()                \r\n");
      out.write("      {                                         \r\n");
      out.write("         //alert(\"테스트\");                       \r\n");
      out.write("                                               \r\n");
      out.write("         $(this).removeClass(\"btn-secondary\"); \r\n");
      out.write("         $(this).addClass(\"btn-primary\");      \r\n");
      out.write("      }, function()                             \r\n");
      out.write("      {                                         \r\n");
      out.write("         $(this).removeClass(\"btn-primary\");   \r\n");
      out.write("         $(this).addClass(\"btn-secondary\");    \r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      $(\".item\").click(function()\r\n");
      out.write("\t  {\r\n");
      out.write("\t\t\t//alert(\"카테고리선택\");\r\n");
      out.write("\t\t\t//alert($(this).children(\".cateItem\").val());\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\tlocation.href = \"categorySelect.action?categoryName=\" + $(this).children(\".cateItem\").val();\r\n");
      out.write("\t  });\r\n");
      out.write("    \t\t    \r\n");
      out.write("  \r\n");
      out.write("   })\r\n");
      out.write("\t\r\n");
      out.write("   function needSignUp()\r\n");
      out.write("   {\r\n");
      out.write("\t\talert(\"로그인이 필요한 서비스입니다. 로그인후 이용해 주세요\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String u_id = (String)session.getAttribute("u_id");
	
	if(u_id != null)
	{	

      out.write("\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
	}
	else
	{

      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("   \t\t");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
	} 
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<!-- 220610 추가한 부분 지워도 됩니다! 큼직하게 이미지 넣는게 밀도있을 것 같아보여서 추가했어요 -->\r\n");
      out.write("<section>\r\n");
      out.write("  <!-- \t<img src=\"images/comfit_main.jpg\" alt=\"\"  style=\"background-size: cover; width: 100%; height: 500px;\" /> -->\r\n");
      out.write("  <div class=\"position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center\" style=\"border: ;\">\r\n");
      out.write("\t<div class='box' style=\"border: 2px solid gray\">\r\n");
      out.write("\t  <div class='wave -one'></div>\r\n");
      out.write("\t  <div class='wave -two'></div>\r\n");
      out.write("\t  <div class='wave -three'></div>\r\n");
      out.write("\t  <div class='title col-md-5 p-lg-5 mx-auto my-5'>\r\n");
      out.write("\t\t  <h1 class=\"display-4 fw-normal animate__animated animate__lightSpeedInRight\"><b>COMFIT</b></h1>\r\n");
      out.write("\t      <!-- <p class=\"lead fw-normal animate__animated animate__bounceInLeft\">나에게 딱! 맞는 컴퓨터</p> -->\r\n");
      out.write("\t      <h3>지금 나에게 딱!! 맞는 컴퓨터</h3>\r\n");
      out.write("\t      <a class=\"btn btn-outline-secondary animate__animated animate__fadeIn\" href=\"#\" style=\"margin-top: 50px\">어서옵쇼</a>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>   \r\n");
      out.write("  </div>\r\n");
      out.write("</section>  \r\n");
      out.write("<!-- 220610 추가한 부분 -->  \r\n");
      out.write("\r\n");
      out.write("<!-- 카테고리 -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("      <div class=\"MultiCarousel\" data-items=\"1,3,5,6\" data-slide=\"1\" id=\"MultiCarousel\"  data-interval=\"1000\">\r\n");
      out.write("            <div class=\"MultiCarousel-inner\">\r\n");
      out.write("            \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"btn btn-primary leftLst\"> <i class=\"bi bi-arrow-left\"></i> </button>\r\n");
      out.write("            <button class=\"btn btn-primary rightLst\"> <i class=\"bi bi-arrow-right\"></i> </button>\r\n");
      out.write("        </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <br />\r\n");
      out.write("   \r\n");
      out.write("   <hr />\r\n");
      out.write("   \r\n");
      out.write("   <br />\r\n");
      out.write("   \r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("       \r\n");
      out.write("      <!-- 최근 등록 상품 -->\r\n");
      out.write("      <div style=\"font-size: 20pt; font-weight:bold; display: inline-block; width: 1100px;\">\r\n");
      out.write("         최근 등록 상품\r\n");
      out.write("      </div>\r\n");
      out.write("         \r\n");
      out.write("      \r\n");
      out.write("      <br /><br />\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("       <div class=\"col-md-12 text-center\">\r\n");
      out.write("   \r\n");
      out.write("         <div class=\"newList\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </div>\t<!-- close.newList -->\r\n");
      out.write("         <br />   \r\n");
      out.write("      </div><!-- close.col-md-12 text-center -->\r\n");
      out.write("      <hr />\r\n");
      out.write("      <br />   \r\n");
      out.write("      <!-- 인기 상품 -->\r\n");
      out.write("      <div style=\"font-size: 20pt; font-weight:bold; display: inline-block; width: 1100px;\">\r\n");
      out.write("         인기 상품\r\n");
      out.write("      </div>\r\n");
      out.write("         \r\n");
      out.write("      <br /><br />\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-md-12 text-center\">\r\n");
      out.write("   \r\n");
      out.write("         <div class=\"newList\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"images/ssd.jpg\" class=\"card-img-top\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">SSD</h5>\r\n");
      out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">120,000</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary hover\" style=\"margin: auto; display: block;\">상세페이지</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"images/ssd.jpg\" class=\"card-img-top\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">SSD</h5>\r\n");
      out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">120,000</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary hover\" style=\"margin: auto; display: block;\">상세페이지</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"images/ssd.jpg\" class=\"card-img-top\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">SSD</h5>\r\n");
      out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">120,000</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary hover\" style=\"margin: auto; display: block;\">상세페이지</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"images/ssd.jpg\" class=\"card-img-top\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">SSD</h5>\r\n");
      out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">120,000</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary\" style=\"margin: auto; display: block;\">상세페이지</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"images/ssd.jpg\" class=\"card-img-top\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">SSD</h5>\r\n");
      out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">120,000</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary\" style=\"margin: auto; display: block;\">상세페이지</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"images/ssd.jpg\" class=\"card-img-top\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">SSD</h5>\r\n");
      out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">120,000</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary hover\" style=\"margin: auto; display: block;\">상세페이지</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"images/ssd.jpg\" class=\"card-img-top\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">SSD</h5>\r\n");
      out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">120,000</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary hover\" style=\"margin: auto; display: block;\">상세페이지</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"images/ssd.jpg\" class=\"card-img-top\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">SSD</h5>\r\n");
      out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">120,000</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary hover\" style=\"margin: auto; display: block;\">상세페이지</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"images/ssd.jpg\" class=\"card-img-top\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">SSD</h5>\r\n");
      out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">120,000</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary hover\" style=\"margin: auto; display: block;\">상세페이지</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("               <img src=\"images/ssd.jpg\" class=\"card-img-top\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">SSD</h5>\r\n");
      out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">120,000</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-secondary hover\" style=\"margin: auto; display: block;\">상세페이지</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("         </div>\r\n");
      out.write("                        \r\n");
      out.write("      </div>\r\n");
      out.write("         \r\n");
      out.write("   </div>           \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/view/user/main/non_user_main.jsp(324,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/view/user/main/comfit_header_user.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/view/user/main/non_user_main.jsp(331,5) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/WEB-INF/view/user/main/comfit_header_nolog.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/user/main/non_user_main.jsp(359,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("category");
      // /WEB-INF/view/user/main/non_user_main.jsp(359,13) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cateList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            \t\t<div class=\"item\" >\r\n");
            out.write("            \t\t\t<input class=\"cateItem\" type=\"hidden\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.category_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"/>\r\n");
            out.write("                    \t<div class=\"pad15 shadow rounded\" style=\"align-items: center;\">\r\n");
            out.write("                       \t <p class=\"lead\" style=\"font-size: large; margin-top: 8px; margin-bottom: 8px;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.category_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                   \t\t</div>\r\n");
            out.write("                   \t</div>\r\n");
            out.write("            \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/view/user/main/non_user_main.jsp(392,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("product");
      // /WEB-INF/view/user/main/non_user_main.jsp(392,12) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/view/user/main/non_user_main.jsp(392,12) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1);
      // /WEB-INF/view/user/main/non_user_main.jsp(392,12) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(15);
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("         \t   <div class=\"card\">\r\n");
            out.write("            \t   <!-- <img src=\"images/ssd.jpg\" class=\"card-img-top\"> -->\r\n");
            out.write("            \t   <img alt=\"\" src=\"images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pd_photo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\tclass=\"card-img-top\" style=\"width: 220px; height: 140px;\">\r\n");
            out.write("            \t   \r\n");
            out.write("              \t <div class=\"card-body\">\r\n");
            out.write("                  <h5 class=\"card-title\" style=\"text-align: center;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pd_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("                  <p class=\"card-text\"  style=\"text-align: center;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                  ");
            out.write("\r\n");
            out.write("                  <button type=\"button\" class=\"btn btn-secondary hover\"\r\n");
            out.write("                   style=\"margin: auto; display: block;\" onclick=\"needSignUp()\">상세페이지</button>\r\n");
            out.write("               \t</div>\r\n");
            out.write("            </div>\t\t\r\n");
            out.write("         \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f2_reused = false;
    try {
      _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f2.setParent(null);
      // /WEB-INF/view/user/main/non_user_main.jsp(516,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setUrl("/WEB-INF/view/user/main/footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
        if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
      _jspx_th_c_005fimport_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f2_reused);
    }
    return false;
  }
}
