/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-06-18 13:30:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fdirect_005fseller_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Final_Project_ComFIt/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comfit/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1655351634840L));
    _jspx_dependants.put("jar:file:/C:/Final_Project_ComFIt/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comfit/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   request.setCharacterEncoding("UTF-8");
   String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>직거래 판매글 등록</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(cp );
      out.write("/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(cp );
      out.write("/css/inputstyle.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\" type=\"text/css\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(cp );
      out.write("/css/inputstyle.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cp );
      out.write("/css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(cp );
      out.write("/css/timepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(cp );
      out.write("/css/timepicker.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script src=\"jQuery.MultiFile.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".insert {\r\n");
      out.write("    padding: 20px 30px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 75%;\r\n");
      out.write("    height: 15%;\r\n");
      out.write("    border: 1px solid #dbdbdb;\r\n");
      out.write("    -webkit-box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".insert .file-list {\r\n");
      out.write("    height: 15%;\r\n");
      out.write("    overflow: auto;\r\n");
      out.write("    border: 1px solid #989898;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("}\r\n");
      out.write(".insert .file-list .filebox p {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".insert .file-list .filebox .delete i\r\n");
      out.write("{\r\n");
      out.write("    size:50%;\r\n");
      out.write("    margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(\"#category-select\").change(function()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t//alert($(this).val());\r\n");
      out.write("\t\t\t\tvar param = \"optionValue=\" + $(this).val();\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t// select option value 에  카테고리id가 들어가도록 변경\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax(\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\turl: \"changeMakerSelect.action\"\r\n");
      out.write("\t\t\t\t\t, type: \"GET\"\r\n");
      out.write("\t\t\t\t\t, data: param\r\n");
      out.write("\t\t\t\t\t, success: function(result)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#maker_id\").html(result)\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t/* $(\"#maker_name\").html(\"");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\") */\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t, error: function(e)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\talert(e.responseText);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String u_id = (String)session.getAttribute("u_id");
	
	if(u_id != null)
	{	

      out.write("\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
	}
	else
	{

      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("   \t\t");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
	} 
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!--날짜 처리  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(cp);
      out.write("/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(cp);
      out.write("/js/jquery.timepicker.js.\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(cp);
      out.write("/js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("      \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   //$();\r\n");
      out.write("   //jquery();\r\n");
      out.write("   $(document).ready(function()\r\n");
      out.write("   {\r\n");
      out.write("      \r\n");
      out.write("      //시작하는 날\r\n");
      out.write("      $(\"#sdate\").datepicker(\r\n");
      out.write("      {\r\n");
      out.write("         \r\n");
      out.write("         dateFormat: \"yy-mm-dd\" \r\n");
      out.write("         ,minDate:0\r\n");
      out.write("         ,maxDate:+3\r\n");
      out.write("         ,onSelect: function(selectedDate) \r\n");
      out.write("         {    \r\n");
      out.write("        \t \tvar sdate = new Date(selectedDate)\r\n");
      out.write("        \t \tsdate.setDate(sdate.getDate() + 1);\r\n");
      out.write("        \t \t\r\n");
      out.write("        \t \tvar edate = new Date(sdate);\r\n");
      out.write("        \t \tedate.setDate(edate.getDate() + 4);\r\n");
      out.write("        \t \t\r\n");
      out.write("        \t    $(\"#edate\").datepicker({ \r\n");
      out.write("        \t          dateFormat: \"yy-mm-dd\" \r\n");
      out.write("        \t          , minDate: sdate\r\n");
      out.write("        \t          , maxDate: edate\r\n");
      out.write("        \t     });\r\n");
      out.write("         } \r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("      //시간 설정\r\n");
      out.write("      $(function() \r\n");
      out.write("      {\r\n");
      out.write("    \t  var today =  new Date();\r\n");
      out.write("         //시작시간\r\n");
      out.write("          $(\"#time1\").timepicker( {\r\n");
      out.write("              timeFormat: 'H:mm p'\r\n");
      out.write("              ,interval:60\r\n");
      out.write("              ,dynamic: false\r\n");
      out.write("              ,startTime: today.getHours() + ':00'\r\n");
      out.write("              ,maxTime: '11:00pm'\r\n");
      out.write("              ,dropdown: true\r\n");
      out.write("              ,scrollbar: true  \r\n");
      out.write("              ,change: function(time)\r\n");
      out.write("\t\t\t{\t\r\n");
      out.write("            \t  var stime = new Date(time);\r\n");
      out.write("            \t  $(\"#time2\").timepicker({\r\n");
      out.write("                      timeFormat: 'H:mm p'\r\n");
      out.write("                      ,interval: 60\r\n");
      out.write("                      ,dynamic: false\r\n");
      out.write("                      ,minTime: (stime.getHours()+1)+ ':00'\r\n");
      out.write("                      ,maxTime : '23:00'\r\n");
      out.write("                      ,dropdown: true\r\n");
      out.write("                      ,scrollbar: true  \r\n");
      out.write("                      \r\n");
      out.write("                  });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("          });\r\n");
      out.write("         //끝나는 시간\r\n");
      out.write("         \r\n");
      out.write("      });\r\n");
      out.write("   })\r\n");
      out.write("   \r\n");
      out.write("  /* \r\n");
      out.write("$(document).ready(function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$(\"#placeBtn\").click(function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar params = \"pd_title=\" + $(\"#pd_title\").val() + \"&category_name=\" + $(\"#category_select\").val() + \"&maker_id=\" + $(\"#maker_id\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax(\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\turl: \"geotest.action\"\r\n");
      out.write("\t\t\t\t,type: \"GET\"\r\n");
      out.write("\t\t\t\t, data: { \"pd_title\": $(\"#pd_title\").val(),  }\r\n");
      out.write("\t\t\t\t, success: function(data)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tlocation.href=\"geotest.action\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t, error: function(e)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(e.responseText);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("   */\r\n");
      out.write("   \r\n");
      out.write("   $(document).ready(function()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t$(\"#placeBtn\").click(function()\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar child;\r\n");
      out.write("\t\t\t\t\t   child = window.open(\"GeoTest.jsp\", \"_blank\", \"height:100, width:100\");\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("   \r\n");
      out.write("\t$(document).ready(function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// 주소 검색 open \r\n");
      out.write("\t\t$(\"#basic-addon2\").click(function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//alert(\"123\");\r\n");
      out.write("\t\t\tvar child;\r\n");
      out.write("\t\t\tchild = window.open(\"GeoTest.jsp\", \"_blank\", \"width=500, height=400, resizeable=no\");\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// as 불가능 버튼 누르면 value none 설정\r\n");
      out.write("\t$(document).ready(function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$(\"input[name=pd_as_id]\").change(function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//alert($(this).val());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif ($(this).val() == \"3\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t $(\"#pd_asDate\").val('none');\r\n");
      out.write("\t\t\t\t $(\"#pd_asDate\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t$(\"#pd_asDate\").attr(\"readonly\", false);\r\n");
      out.write("\t\t\t\t$(\"#pd_asDate\").val(\"\");\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\t $(document).ready(function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$(\"#direct_insert\").click(function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//alert($(\"input[name=cf_price]\").val());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#direform\").submit();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<div class=\"container\" style=\"padding-top: 80px;\">\r\n");
      out.write("   <p class=\"fs-3\" style=\"font-weight: bold;\">\r\n");
      out.write("      직거래 판매글 등록   \r\n");
      out.write("   </p>\r\n");
      out.write("   \r\n");
      out.write("   <div class=\"input_box\" style=\"padding-left: 5%; padding-top: 10%;\">\r\n");
      out.write("   <form action=\"direct_seller_ok.jsp\" method=\"post\" id=\"direform\" enctype=\"multipart/form-data\">\r\n");
      out.write("      <table style=\"width: 100%;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <tr>\r\n");
      out.write("\t\t\t<th>물품검색<span class=\"star\">*</span></th>\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<div><!--  class=\"input-group mb-6\" -->\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"<!-- form-control  -->\" placeholder=\"판매할 물품을 검색해주세요\" style=\"height:40px; width: 260px; display: inline-block; font-style: italic;\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t<span class=\"input-group-text\" id=\"basic-addon1\" onclick=\"location.href='searchproduct2.action';\" style=\"width: 50px; display: inline-block;\"><i class=\"bi bi-search\"></i></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>제목<span class=\"star\">*</span></th>\r\n");
      out.write("\t\t\t<td colspan=\"3\"><input class=\"form-control\" id=\"pd_title\" name=\"pd_title\" type=\"text\" placeholder=\"제목을 입력해주세요.\" style=\"width: 86%; font-style: italic;\"/>\r\n");
      out.write("\t\t\t<p align=\"right\" style=\"font-size: 3px; margin-right: 16%;\"></p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>물품 카테고리<span class=\"star\">*</span>\r\n");
      out.write("\t\t\t <p style=\"font-weight: normal; font-size: 7pt;\">상품과 일치하는 카테고리를 선택해주세요.\r\n");
      out.write("                <br>적합하지 않을 경우 운영자에 의해 조정될 수 있습니다.</p>\r\n");
      out.write("               </th>\r\n");
      out.write("\t\t\t<td><!-- 카테고리 -->\r\n");
      out.write("\t\t\t\t<select class=\"form-select\" id=\"category-select\" name=\"category_select\" style=\"width: 90%; height: 35px;\">\r\n");
      out.write("\t\t\t\t<option>카테고리 선택</option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td id=\"maker_c\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<select class=\"form-select\" id=\"maker_id\" name=\"pd_maker_id\" style=\"width: 90%; height: 35px;\">\r\n");
      out.write("\t\t\t\t<option id=\"pd_maker\">제조사 카테고리 선택</option>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"pd_name\" name=\"pd_name\" placeholder=\"물품명을 입력해 주세요.\" style=\"width: 90%;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t</td>\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>거래 희망 장소<span class=\"star\">*</span></th>\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<div><!--  class=\"input-group mb-6\" -->\r\n");
      out.write("\t\t\t\t  <input type=\"text\" class=\"<!-- form-control  -->\" id=\"pd_hope_place\" name=\"pd_hope_place\"  placeholder=\"거래 희망장소를 선택해주세요\" style=\"height:40px; width: 500px; display: inline-block; font-style: italic;\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t  <span class=\"input-group-text\" id=\"basic-addon2\" style=\"width: 50px; display: inline-block;\"><i class=\"bi bi-search\"></i></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("            <!-- 지도 출력 -->\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <tr>\r\n");
      out.write("         <div>\r\n");
      out.write("            <th>거래 희망 일시<span class=\"star\">*</span>\r\n");
      out.write("            \t<p style=\"font-weight: normal; font-size: 7pt;\">오늘날짜로 선택이 불가능합니다.\r\n");
      out.write("            \t<br>거래 가능일은 5일입니다.\r\n");
      out.write("            \t<br>끝나는 시간은 23:00 PM 까지 입니다.</p>\r\n");
      out.write("            \r\n");
      out.write("\t            <td>\r\n");
      out.write("\t\t\t\t\t<!-- <div class=\"input-group input-daterange\" > -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"sdate\" name=\"pd_hope_sdate\" placeholder=\"1. 거래를 시작할 날짜\" style=\"width: 90%;\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t            </td>\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t           \t<td>\r\n");
      out.write("\t               <!-- <div class=\"input-group input-daterange\"> -->\r\n");
      out.write("\t                   <input type=\"text\" class=\"form-control\" id=\"edate\" name=\"pd_hope_edate\" placeholder=\"2. 거래를 끝낼 날짜\" style=\"width: 90%;\"/>\r\n");
      out.write("\t               </div>\r\n");
      out.write("\t            </td>\r\n");
      out.write("            <tr>\r\n");
      out.write("            <th></th>\r\n");
      out.write("\t            <td>\r\n");
      out.write("\t             \t<!-- <div class=\"input-group input-daterange\"> -->\r\n");
      out.write("\t                \t<input type=\"text\" class=\"form-control\" id=\"time1\" name=\"pd_hope_stime\"placeholder=\"3. 거래 시작 시간 선택\" style=\"width: 90%;\"/>\r\n");
      out.write("\t             \t</div>\r\n");
      out.write("\t            </td>\r\n");
      out.write("                <td>\r\n");
      out.write("\t\t            <!-- <div class=\"input-group input-daterange\"> -->\r\n");
      out.write("\t\t                  <input type=\"text\" class=\"form-control\" id=\"time2\" name=\"pd_hope_etime\" placeholder=\"4. 거래 종료 시간 선택\" style=\"width: 90%;\"/>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>   \r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("        \r\n");
      out.write("         \r\n");
      out.write("\t\t<tr>\r\n");
      out.write("            <th>희망 시작 가격<span class=\"star\">*</span>\r\n");
      out.write("             \t<p style=\"font-weight: normal; font-size: 7pt;\">희망하는 가격을 적어주세요.</p>\r\n");
      out.write("            </th>\r\n");
      out.write("            <td colspan=\"1\">\r\n");
      out.write("              \t<input class=\"form-control\" id=\"price1\" name=\"pd_hopeprice\" type=\"text\" placeholder=\"희망 가격을 입력해주세요.\" style=\"width: 90%;\"/>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>\r\n");
      out.write("               \t<div style=\"display: inline-block; font-style: italic; color:red; font-size: small;\"> ※comfit 추천 가격 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${realAvgPrice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</div>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("               \r\n");
      out.write("\t\t<tr>\r\n");
      out.write("          <th>물품 사진<span class=\"star\">*</span>\r\n");
      out.write("           <p style=\"font-weight: normal; font-size: 7pt;\">최소 3장 이상 등록해 주세요.</p>\r\n");
      out.write("              </th>\r\n");
      out.write("              <td colspan=\"3\">\r\n");
      out.write("                    <div class=\"insert\">\r\n");
      out.write("                    <p style=\"font-weight: normal;\">[ 최소 3장 ~ 최대 5장 ]</p>\r\n");
      out.write("                     <input type=\"file\" name=\"uploadFile\"  />\r\n");
      out.write("                     <div class=\"file-list\"  >\r\n");
      out.write("                     </div>\r\n");
      out.write("                </div>\r\n");
      out.write("          \t</td>\r\n");
      out.write("       \t</tr>\r\n");
      out.write("         \r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>A/S 가능 여부\r\n");
      out.write("                </th>\r\n");
      out.write("                <td colspan=\"3\">\r\n");
      out.write("                <div class=\"form-check form-check-inline\">\r\n");
      out.write("              <input class=\"form-check-input\" type=\"radio\" name=\"pd_as_id\" id=\"inlineRadio1\" value=\"1\" checked=\"checked\">\r\n");
      out.write("              <label class=\"form-check-label\" for=\"inlineRadio1\">유상</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-check form-check-inline\">\r\n");
      out.write("              <input class=\"form-check-input\" type=\"radio\" name=\"pd_as_id\" id=\"inlineRadio2\" value=\"2\">\r\n");
      out.write("              <label class=\"form-check-label\" for=\"inlineRadio2\">무상</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-check form-check-inline\">\r\n");
      out.write("              <input class=\"form-check-input\" type=\"radio\" name=\"pd_as_id\" id=\"inlineRadio3\" value=\"3\">\r\n");
      out.write("              <label class=\"form-check-label\" for=\"inlineRadio3\">불가능</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <input class=\"form-control\" id=\"pd_asDate\" name=\"pd_as_remain\" type=\"text\" placeholder=\"AS 만료 기간 입력. 예) 2024-09\" style=\"width: 86%;\"/>\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>\r\n");
      out.write("               <div style=\"background-color: #C9E0F5; height: 70px; padding: 10px; width: 85%;\">\r\n");
      out.write("                  <p style=\"font-size: 9pt;\"> ※ 게시글 유지 기간</p>\r\n");
      out.write("                  <p style=\"font-size: 7pt; font-weight: normal;\">게시글 등록 시간부터 00일까지 유지됩니다.</p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </th>\r\n");
      out.write("            \r\n");
      out.write("            <td colspan=\"3\" rowspan=\"2\">\r\n");
      out.write("            <textarea placeholder=\" 판매자 코멘트 작성\" id=\"comments\" name=\"comments\" style=\"width:86%; height: 150px;\"></textarea>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("\t\t<tr>\r\n");
      out.write("            <th style=\"margin-right: 10%;\">\r\n");
      out.write("               \t<div style=\"background-color: #C9E0F5; height: 100px; padding: 10px; width: 85%;\">\r\n");
      out.write("\t\t\t\t\t<p style=\"font-size: 9pt;\"> ※ 코멘트 작성 시 주의사항</p>\r\n");
      out.write("                  \t<p style=\"font-size: 7pt; font-weight: normal;\">불필요한 개인 정보 노출 및 판매와 관련없는 문구\r\n");
      out.write("                  \t<br>등록 시 약관에 위배되어 제재될 수 있습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("         \r\n");
      out.write("\t\t<tr>\r\n");
      out.write("            <td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<div class=\"d-grid gap-2 d-md-flex justify-content-md-end\" style=\"width: 90%;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"address\" style=\"display: none;\" name=\"pd_hope_mgrs\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"cf_price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${realAvgPrice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"display: none;\" />\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"direct_insert\">등록하기</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\">취소</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("         \r\n");
      out.write("      </table>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <br />\r\n");
      out.write("   <br />\r\n");
      out.write("   <br />\r\n");
      out.write("   <br />\r\n");
      out.write("   <br />\r\n");
      out.write("   <br />\r\n");
      out.write("   <br />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/user/main/user_direct_seller_edit.jsp(76,31) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("maker");
      // /WEB-INF/view/user/main/user_direct_seller_edit.jsp(76,31) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${makerlist }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t+ \"<option value='");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maker.maker_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'>\" + ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maker.maker_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("+ \"</option>\"\r\n");
            out.write("\t\t\t\t\t\t\t\t+\"");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/view/user/main/user_direct_seller_edit.jsp(105,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/view/user/main/comfit_header_user.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/view/user/main/user_direct_seller_edit.jsp(112,5) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/WEB-INF/view/user/main/comfit_header_nolog.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/view/user/main/user_direct_seller_edit.jsp(306,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("category");
      // /WEB-INF/view/user/main/user_direct_seller_edit.jsp(306,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categorylist }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<option class=\"option_select\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.pd_category_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.category_name eq cate ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.category_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/view/user/main/user_direct_seller_edit.jsp(318,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("maker");
      // /WEB-INF/view/user/main/user_direct_seller_edit.jsp(318,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${makerlist }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maker.pd_maker_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maker.maker_name eq mk ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maker.maker_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
