/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-06-06 06:34:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fmypage_005fsell_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1654491837648L));
    _jspx_dependants.put("jar:file:/C:/Final_Project_ComFIt/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comfit/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>내 판매 목록</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".list-group {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("\tmargin-left: 11%;\r\n");
      out.write("\tfont-family: 맑은 고딕;\r\n");
      out.write("\tfont-size: 30pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".list-group-item {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".container\r\n");
      out.write("{\r\n");
      out.write("\tmargin-left: 5%;\r\n");
      out.write("}\r\n");
      out.write("h5\r\n");
      out.write("{\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<!-- 헤더 영역 -->\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"title\">\r\n");
      out.write("\t\t마이페이지 &nbsp;&nbsp;<span style=\"font-size: 20pt;\">판매내역</span>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 col-sm-12 col-lg-1\" style=\"margin-left: 3%;\">\r\n");
      out.write("\t\t\t\t<div class=\"list-group \">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"list-group-item list-group-item-action\">회원정보</a>\r\n");
      out.write("\t\t\t\t\t<br /> <a href=\"#\" class=\"list-group-item list-group-item-action\">구매내역</a>\r\n");
      out.write("\t\t\t\t\t<br /> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"list-group-item list-group-item-action active\">판매내역</a> <br />\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"list-group-item list-group-item-action\">입출금내역</a>\r\n");
      out.write("\t\t\t\t\t<br /> <a href=\"#\" class=\"list-group-item list-group-item-action\">회원탈퇴</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-10 col-sm-12 col-md-12\"  style=\"margin-left: 4%;\">\r\n");
      out.write("\t\t\t\t<div class=\"d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t<p style=\"font-size: 18pt; font-weight: bolder;\">내 판매</p>\r\n");
      out.write("\t\t\t\t\t<select class=\"selectpicker\" style=\"width: 100px; text-align: center; height: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t<option>날짜순</option>\r\n");
      out.write("\t\t\t\t\t\t<option>완료</option>\r\n");
      out.write("\t\t\t\t\t\t<option>미완료</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 테이블  -->\r\n");
      out.write("\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-bordered\" style=\"font-size: 10pt;\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>판매 시작일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>최종 금액</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>상품정보</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>방식</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>예정 장소</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>직거래 예정 일시</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>실제 거래 일시</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>상태</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2022-05-17</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>40,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>레이저 무선 마우스</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>배송(경매)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\">인천 계양구 새빛 아파트 104동 203호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>낙찰</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2022-04-30</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>80,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>커세어 무선 헤드셋</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>직거래(구매제안)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\">인천 계양구 새빛 아파트 경비실 뒤</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\">2022-05-18 18시30분</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>채택 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"sellBtn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 60px; height: 30px; font-size: 6pt;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-bs-toggle=\"modal\" data-bs-target=\"#directSellCheck\">판매확정</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"danger\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 60px; height: 30px; font-size: 6pt;\">신고하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2022-05-17</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>40,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>레이저 무선 마우스</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>배송(경매)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\">인천 계양구 새빛 아파트 104동 앞</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>채택 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"sellBtn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 60px; height: 30px; font-size: 6pt;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-bs-toggle=\"modal\" data-bs-target=\"#sellCheck\">판매확정</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"danger\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 60px; height: 30px; font-size: 6pt;\">신고하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2022-05-17</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>40,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>레이저 무선 마우스</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>배송(경매)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\">인천 계양구 새빛 아파트 104동 앞</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>낙찰</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2022-05-17</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>40,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>레이저 무선 마우스</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>배송(경매)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"font-size: 8pt;\">인천 계양구 새빛 아파트 104동 앞</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>낙찰</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<!-- Modal 운송장 번호 입력 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"sellCheck\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">판매확정하기</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("         <h5 style=\"font-weight: bold;\">제품명</h5>\r\n");
      out.write("         레이저 무선 마우스<br />\r\n");
      out.write("         \r\n");
      out.write("         가격 : 40,000원<br />\r\n");
      out.write("         낙찰일시 : 2022-05-17 13시 37분<br />\r\n");
      out.write("         <br />\r\n");
      out.write("         운송장번호를 입력해 주세요. <br />\r\n");
      out.write("         <form action=\"\">\r\n");
      out.write("         \t<select id=\"express\" class=\"form-select\" style=\"width: 30%; margin-top: 2%;\">\r\n");
      out.write("         \t\t<option value=\"1\">cj대한통운</option>\r\n");
      out.write("         \t\t<option value=\"2\">우체국</option>\r\n");
      out.write("         \t\t<option value=\"3\">한진</option>\r\n");
      out.write("         \t\t<option value=\"4\">롯데</option>\r\n");
      out.write("         \t\t<option value=\"5\">로젠</option>\r\n");
      out.write("         \t\t<option value=\"6\">GS25편의점</option>\r\n");
      out.write("         \t</select>\r\n");
      out.write("         \t<input type=\"text\" id=\"expressNum\" placeholder=\"운송장번호\" style=\"width: 70%; margin-top: 2%;\">\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("      \t<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("        data-bs-toggle=\"modal\" data-bs-target=\"#sellCheckOk\">확인</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal 운송장 번호 확인 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"sellCheckOk\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("         <h5 style=\"font-weight: bold;\">제품명</h5>\r\n");
      out.write("         레이저 무선 마우스<br />\r\n");
      out.write("         \r\n");
      out.write("         가격 : 40,000원<br />\r\n");
      out.write("         낙찰일시 : 2022-05-17 13시 37분<br />\r\n");
      out.write("         <br />\r\n");
      out.write("       \t <h4 style=\"font-weight: bold;\">판매가 확정되었습니다!</h4> \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" aria-label=\"Close\" data-bs-dismiss=\"modal\">확인</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal 직거래 판매확정  -->\r\n");
      out.write("<div class=\"modal fade\" id=\"directSellCheck\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">판매확정하기</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("         <h5 style=\"font-weight: bold;\">제품명</h5>\r\n");
      out.write("         커세어 무선 헤드셋<br />\r\n");
      out.write("         \r\n");
      out.write("         가격 : 40,000원<br />\r\n");
      out.write("         낙찰일시 : 2022-04-30 21시 25분<br />\r\n");
      out.write("         <h5 style=\"font-weight: bold;\">내 판매 코드 : vkgikwo </h5>\r\n");
      out.write("         <br />\r\n");
      out.write("         <form action=\"\">\r\n");
      out.write("         \t<h5>상대방 코드를 입력해 주세요.</h5>\r\n");
      out.write("         \t<input type=\"text\" id=\"buyerCode\" placeholder=\"구매자 코드\" style=\"width: 90%; margin-top: 2px;\">\r\n");
      out.write("         \t<br /><br />\r\n");
      out.write("         \t<h5>한줄 후기를 입력해 주세요</h5>\r\n");
      out.write("         \t<input type=\"text\" id=\"review\" placeholder=\"한줄 후기 입력\" style=\"width: 90%; margin-top: 2px;\">\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("      \t<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("        data-bs-toggle=\"modal\" data-bs-target=\"#directSellCheckOk\">확인</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal 직거래 판매 확인 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"directSellCheckOk\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <h5 style=\"font-weight: bold;\">제품명</h5>\r\n");
      out.write("         커세어 무선 헤드셋<br />\r\n");
      out.write("         \r\n");
      out.write("         가격 : 40,000원<br />\r\n");
      out.write("         낙찰일시 : 2022-04-30 21시 25분<br />\r\n");
      out.write("         <h5 style=\"font-weight: bold;\">내 판매 코드 : vkgikwo </h5>\r\n");
      out.write("         <br />\r\n");
      out.write("       \t <h4 style=\"font-weight: bold;\">판매가 확정되었습니다!</h4> \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" aria-label=\"Close\" data-bs-dismiss=\"modal\">확인</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /user_mypage_sell_list.jsp(51,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("comfit_header_user.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }
}
