/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-06-07 11:58:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fdelivery_005fnon_005fseller_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Final_Project_ComFIt/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comfit/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1654491837648L));
    _jspx_dependants.put("jar:file:/C:/Final_Project_ComFIt/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comfit/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   request.setCharacterEncoding("UTF-8");
   String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<title>배송 상품 페이지.jsp</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(cp );
      out.write("/css/bootstrap.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/bootstrap.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("p\r\n");
      out.write("{\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("}\r\n");
      out.write("/* 내용 div */\r\n");
      out.write(".content\r\n");
      out.write("{\r\n");
      out.write("\tpadding: 4%;\r\n");
      out.write("}\r\n");
      out.write("/* 내용 안에 들어가는 p */\r\n");
      out.write(".content_text\r\n");
      out.write("{\r\n");
      out.write("\tfont-size: 15pt; \r\n");
      out.write("\tfont-weight: bold; \r\n");
      out.write("\tline-height: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 유저 사진 */\r\n");
      out.write(".user_image\r\n");
      out.write("{\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("}\r\n");
      out.write("th,td\r\n");
      out.write("{\r\n");
      out.write("\tborder: 1px solid #444444;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("d-block\r\n");
      out.write("{\r\n");
      out.write("\twidth: 100%; \r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" .carousel-inner > .carousel-item > img \r\n");
      out.write(" {\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      min-width: 100%;\r\n");
      out.write("      max-width: 100%;\r\n");
      out.write("      min-height: 380px;\r\n");
      out.write("      max-height: 380px;\r\n");
      out.write("      object-fit: cover;\r\n");
      out.write("  } \r\n");
      out.write("\r\n");
      out.write("carousel-item\r\n");
      out.write("\r\n");
      out.write("/* 사진 전체 */\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div style=\"padding-top: 5%;\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<p class=\"fs-4\" style=\"text-align: center; font-weight: bold;\">[카테고리]2022 GTX 0000 아주 합리적인 가격에 드립니다.</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t<div class=\"col-md-6\" style=\"float: left; width: 560px; height: 420px; padding-top: 3%; margin-right: 3%;\">\t\r\n");
      out.write("\t\t\t<div id=\"carouselExampleIndicators\" class=\"carousel slide carousel-fade\" data-bs-touch=\"false\" data-bs-ride=\"true\">\r\n");
      out.write("\t\t\t  <div class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("\t\t\t    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("\t\t\t    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t    <div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t      <img src=\"https://cdn.pixabay.com/photo/2015/09/04/23/28/wordpress-923188__340.jpg\" class=\"d-block w-100 rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"carousel-item\">\r\n");
      out.write("\t\t\t      <img src=\"https://cdn.pixabay.com/photo/2016/03/26/13/09/cup-of-coffee-1280537__340.jpg\" class=\"d-block w-100 rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"carousel-item\">\r\n");
      out.write("\t\t\t      <img src=\"https://cdn.pixabay.com/photo/2016/06/15/16/16/man-1459246__340.png\" class=\"d-block w-100 rounded\" alt=\"...\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("\t\t\t    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("\t\t\t  <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("\t\t\t    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table class=\"col-md-5\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><p>거래방식</p>\r\n");
      out.write("\t\t\t\t<!-- 속성에 따라 직거래/배송 표기 -->\r\n");
      out.write("\t\t\t\t<p class=\"content_text\">배송(경매)</p></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><p>시작가격</p>\r\n");
      out.write("\t\t\t\t<p class=\"content_text\">100,000 원</p></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><p>현재가격</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 입찰최고가가 반영 -->\r\n");
      out.write("\t\t\t\t\t<!-- 입찰이 완료된 상품입니다. -->\r\n");
      out.write("\t\t\t\t\t<!-- <p class=\"content_text\" style=\"color: blue;\">입찰이 완료된 상품입니다.</p> -->\r\n");
      out.write("\t\t\t\t\t<p class=\"content_text\" style=\"color: blue;\">100,000 원</p>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" style=\"border-bottom: 2px solid gray; \"><p>경매 종료까지</p>\r\n");
      out.write("\t\t\t\t<!-- 경매 종료시간 적용/경매 종료시 경매종료라고 표기 -->\r\n");
      out.write("\t\t\t\t<!-- <td colspan=\"2\" style=\"border-bottom: 2px solid gray;\"><p>경매 종료</p> -->\r\n");
      out.write("\t\t\t\t<p class=\"fs-2\" style=\"font-weight: bold;\">[<span class=\"fs-2\" style=\"color: #ffd700;\">08:51:37</span>]</p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 종료 시 최종가 표기  -->\r\n");
      out.write("\t\t\t\t<!-- <p class=\"content_text\" style=\"color: blue;\">최종 가격 : 143,000원</p> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"padding-top: 10px;\">\r\n");
      out.write("\t\t\t\t\t<p>제조사/물품명</p>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th style=\"padding-top: 10px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 제조사/물품명 표기 -->\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold;\">제조사/물품명</p>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<p>즉시구매가격</p>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 즉시구매가 표기 -->\r\n");
      out.write("\t\t\t\t\t<p>143,200원</p>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<p>Comfit 추천가격</p>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t<!-- 상품에 따른 추천가 표기 -->\r\n");
      out.write("\t\t\t\t\t<p style=\"color: blue;\">189,200원</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<!-- 상태에 따라 버튼 변경 -->\r\n");
      out.write("\t\t\t\t<!-- 판매자)입찰자 없을 때 :수정하기/삭제하기-->\r\n");
      out.write("\t\t\t\t<!-- 판매자)입찰자 있을 때 :즉시낙찰/삭제하기 -->\r\n");
      out.write("\t\t\t\t<!-- 구매자) 제안하기/신고 -->\r\n");
      out.write("\t\t\t\t<!-- <button type=\"button\" class=\"btn btn-warning\" style=\"width: 48%;\">즉시낙찰</button> -->\r\n");
      out.write("\t\t\t\t<!-- <button type=\"button\" class=\"btn btn-primary\" style=\"width: 48%;\">제안하기</button> -->\r\n");
      out.write("\t\t\t\t<!-- <button type=\"button\" class=\"btn btn-secondary\" style=\"width: 48%;\">신고</button> -->\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" style=\"width: 48%;\">수정하기</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\" style=\"width: 48%;\">삭제하기</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\" style=\"display: inline-block; float:left;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr class=\"table-secondary\">\r\n");
      out.write("\t\t\t\t\t<th style=\"height:25px; width: 100%; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 18pt;\">상품 상세정보</p>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 공간분리용 tr -->\r\n");
      out.write("\t\t\t\t<tr style=\"height: 10px;\">\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr class=\"table-secondary\">\r\n");
      out.write("\t\t\t\t\t<td style=\"padding:5%;\">\r\n");
      out.write("\t\t\t\t\t<p>상품 상세정보<br><br>\r\n");
      out.write("\t\t\t\t\t1. 제조사 A/S 가능여부 : 무상 5개월까지 가능<br><br>\r\n");
      out.write("\t\t\t\t\t2. 특이사항 : 외관상 흠집 및 오염 없음, 작동상태 양호, 사용기간 3개월\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 구매자) 판매자 정보 -->\r\n");
      out.write("\t\t\t<div class=\"seller_info col-md-5\" style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"card\" style=\"width: 100%; padding:3%;\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div class=\"user_image\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"\" src=\"https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"object-fit:cover; height: 100%; width: 100%;\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"padding-left: 25%;\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"fs-2\" style=\"margin-top: 5%; font-weight: bold;\">아몰랑</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t  <div class=\"card-body\">\r\n");
      out.write("\t\t\t\t    <h5 class=\"card-title\"></h5>\r\n");
      out.write("\t\t\t\t    <p class=\"card-text\">소개글 : 최저가 판매상\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>누적 판매 수 : 25회\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t<br>Level : 5</p>\r\n");
      out.write("\t\t\t\t    <div style=\"text-align: right;\">\r\n");
      out.write("\t\t\t\t    \t<a href=\"#\" style=\"text-decoration: none;\">상세보기</a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 판매자 정보 아래 버튼  -->\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center; margin-top: 1%;\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" style=\"width: 25%; margin-right: 15%;\">목록으로</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" style=\"width: 25%;\">찜하기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 입찰정보가 출력될 폼 -->\r\n");
      out.write("\t\t<div class=\"content_bid\" style=\"margin-top: 5%; margin-left: 5%; margin-right:9%;\">\r\n");
      out.write("\t\t<p class=\"fs-3\" style=\"padding-left: 4%; font-weight: bold;\">현재 입찰 정보</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- 입찰 폼 한개 -->\r\n");
      out.write("\t\t\t<div class=\"shadow p-3 mb-5 bg-body rounded\">\r\n");
      out.write("\t\t\t<table style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width: 20%; padding-left: 3%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"user_image\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"\" src=\"https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"object-fit:cover; height: 100%; width: 100%;\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th style=\"padding-left: 2%;\">\r\n");
      out.write("\t\t\t\t\t<p class=\"fs-4\">\r\n");
      out.write("\t\t\t\t\t김상기\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<p style=\"padding-left:10%;\">가격 : 143,000원<br>\r\n");
      out.write("\t\t\t\t\t배송지 : 서울시 왕십리 111번지</p>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: right; margin-left: 20%;\">\r\n");
      out.write("\t\t\t\t\t<p>22-05-26    10:56 AM</p>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\">낙찰하기</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"shadow p-3 mb-5 bg-body rounded\">\r\n");
      out.write("\t\t\t<table style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width: 20%;padding-left: 3%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"user_image\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"\" src=\"https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"object-fit:cover; height: 100%; width: 100%;\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th style=\"padding-left: 2%;\">\r\n");
      out.write("\t\t\t\t\t<p class=\"fs-4\">\r\n");
      out.write("\t\t\t\t\t김민성\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<p style=\"padding-left:10%;\">가격 : 135,000원<br>\r\n");
      out.write("\t\t\t\t\t배송지 : 인천 새벌로 112번길</p>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: right;\">\r\n");
      out.write("\t\t\t\t\t<p>22-05-26    10:56 AM</p>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<!-- bootstrap card 사용해서 구성 가능 -->\t\r\n");
      out.write("<!-- \r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("  <div class=\"card-header\">\r\n");
      out.write("    Featured\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"card-body\">\r\n");
      out.write("    <h5 class=\"card-title\">Special title treatment</h5>\r\n");
      out.write("    <p class=\"card-text\">With supporting text below as a natural lead-in to additional content.</p>\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-primary\">Go somewhere</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write(" -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\t\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /user_delivery_non_seller.jsp(76,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("comfit_header_user.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }
}
