SELECT USER
FROM DUAL;
--==>>COMFIT

DESC ASK;

SELECT *
FROM ASK;

--○ 문의 삭제 쿼리
DELETE
FROM ASK
WHERE ASK_ID='ask_2';

COMMIT;

--○ 문의 입력 쿼리
INSERT INTO ASK (ASK_ID, ASK_TITLE,ASK_CONTENTS,U_ID,ASK_CATE_ID,ALARM_CODE)
VALUES(CONCAT('ask_',ASK_INSERT_SEQ.NEXTVAL),'뉴','나','test2','3','1');

--○ 시퀀스 생성
CREATE SEQUENCE ASK_INSERT_SEQ
    MAXVALUE 9999999999999999999999999999
    NOCACHE;
    
COMMIT;