SELECT USER
FROM DUAL;
--==>> COMFIT

SELECT *
FROM TAB;

SELECT PD_ID, PD_NAME, PRICE, PD_REGIT_DATE
FROM DELI_PD_LIST_REALVIEW;


SELECT COUNT(*) AS DELI_CHECK_ID
FROM DELIVERY_PRODUCT
WHERE U_ID = 'TEST' AND DELI_PD_ID = '';

SELECT COUNT(*) AS DIRE_CHECK_ID
FROM DIRECT_PRODUCT
WHERE U_ID = 'test2' AND DIRE_PD_ID = 'dire_2';


SELECT *
FROM DELIVERY_PRODUCT;

-- ○ 구매제안 인서트
SELECT *
FROM SUGGEST_LIST;

SELECT *
FROM SEQ;

CREATE SEQUENCE SUGGEST_SEQ
NOCACHE;
--==>> Sequence SUGGEST_SEQ이(가) 생성되었습니다.

INSERT INTO SUGGEST_LIST(SUGGEST_CODE, SUGGEST_PRICE, SUGGEST_TIME, SUGGEST_PLACE, PLACE_DETAIL, U_ID, DIRE_PD_ID)
VALUES(CONCAT('suggest_'), TO_CHAR(SUGGEST_SEQ.NEXTVAL), 가격, 정한시간, 장소, 장소상세, 구매제안자, 직거래상품ID);


CREATE OR REPLACE VIEW MGRS_VIEW
AS
SELECT SUBSTR(PD_HOPE_MGRS, 0, INSTR(PD_HOPE_MGRS, '/', 1)-1) AS LAT
     , SUBSTR(PD_HOPE_MGRS, INSTR(PD_HOPE_MGRS, '/', 1)+1) AS LON
     , DIRE_PD_ID AS PD_ID
FROM DIRECT_PRODUCT;
--==>> View MGRS_VIEW이(가) 생성되었습니다.

SELECT LAT, LON, PD_ID
FROM MGRS_VIEW
WHERE PD_ID = 'dire_1';
--==>> 37.6568258	127.0178972	dire_1



