SELECT PD_ID, PD_TITLE, NVL(PD_PRICE, -1) AS PD_PRICE, SYSTEM, TO_CHAR(PD_REGIT_DATE, 'YYYY-MM-DD') AS PD_REGIT_DATE
, TIME, TO_CHAR(COMP_DATE, 'YYYY-MM-DD') AS COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS
		FROM
		(
		SELECT PD_ID, PD_TITLE, PD_PRICE, SYSTEM, PD_REGIT_DATE, TIME, COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS
		, ROW_NUMBER() OVER(PARTITION BY PD_ID ORDER BY COMP_DATE ASC) AS RN
        FROM MY_PRODUCT_LIST
		WHERE SELLER_ID = 'test1'
		ORDER BY PD_REGIT_DATE DESC
		)
		WHERE RN=1;


SELECT *
FROM INPUT_MONEY;

INSERT INTO INPUT_MONEY(IN_M_ID, IN_MONEY, IN_ACCOUNT, U_ID, BANK_ID)
VALUES('inm_2', 3000000, '941610-11-315477', 'test2', 2);

commit;

SELECT PD_ID, PD_TITLE, PD_PRICE, SYSTEM, TO_CHAR(PD_REGIT_DATE, 'YYYY-MM-DD') AS PD_REGIT_DATE
, TIME, TO_CHAR(COMP_DATE, 'YYYY-MM-DD') AS COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS
FROM MY_PRODUCT_LIST
WHERE BUYER_ID = 'test2'
ORDER BY PD_REGIT_DATE DESC;

select *
from comfit_user;



SELECT *
FROM MY_PRODUCT_LIST;

-- MY_PRODUCT_LIST에 BSE_ID 추가
CREATE OR REPLACE VIEW MY_PRODUCT_LIST
AS
  SELECT DELI_PD_ID AS PD_ID, PD_TITLE, NVL(BID_PRICE, PD_START_PRICE) AS PD_PRICE
, '택배(경매)' AS SYSTEM
, PD_REGIT_DATE, NULL AS TIME, COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS, BS_ID AS BSE_ID
FROM DELI_SELL_LIST
UNION
SELECT DIRE_PD_ID AS PD_ID, PD_TITLE, SUGGEST_PRICE AS PD_PRICE
, '직거래(제안거래)' AS SYSTEM
, PD_REGIT_DATE, SUGGEST_TIME AS TIME, COMP_DATE, SELLER_ID, BUYER_ID, SUGGEST_ADDR AS ADDRESS, STATUS, SELECTED_ID AS BSE_ID
FROM DIRE_SELL_LIST;


--> 구매/판매확정코드 확인도 되는 DETAIL_BUYLIST_VIEW 테이블

CREATE OR REPLACE VIEW DETAIL_BUYLIST_VIEW
AS
SELECT PD_ID, PD_TITLE, PD_PRICE, SYSTEM, TO_CHAR(PD_REGIT_DATE, 'YYYY-MM-DD') AS PD_REGIT_DATE
		, TIME, TO_CHAR(COMP_DATE, 'YYYY-MM-DD') AS COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS
        , SE.SELECTED_ID, TO_CHAR(SE.SELECTED_DATE, 'YYYY-MM-DD') AS SELECTED_DATE, SE.BUYER_CODE, SE.SELLER_CODE
FROM MY_PRODUCT_LIST MPL
LEFT OUTER JOIN SELECTED SE
ON MPL.BSE_ID = SE.SELECTED_ID;



--> 구매리스트 체크하는 테이블을 변경
SELECT PD_ID, PD_TITLE, PD_PRICE, SYSTEM, PD_REGIT_DATE
		, TIME, COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS
        , SELECTED_ID, SELECTED_DATE, BUYER_CODE, SELLER_CODE
		FROM DETAIL_BUYLIST_VIEW
		WHERE BUYER_ID = 'test2'
		ORDER BY PD_REGIT_DATE DESC;


--> 구매확정 시퀀스
CREATE SEQUENCE DIRE_COMPLETE_BUY_SEQ
NOCACHE;

SELECT *
FROM DIRE_COMPLETE_BUY;

-- 인서트문 예시
select *
from selected;

INSERT INTO DIRE_COMPLETE_BUY(DIRE_COMP_BUY_ID,REVIEW, SELECTED_ID)
VALUES(CONCAT('rcBuy',DIRE_COMPLETE_BUY_SEQ.NEXTVAL),'굿!!', 'sel_9');

rollback;

EXEC BUY_COMPLETE_PRC('sel_9', '805RLDYGTUWXABZZ', '감사합니다!')

COMMIT;

SELECT *
FROM DIRE_COMPLETE_BUY;


SELECT PD_ID, PD_TITLE, PD_PRICE, SYSTEM, PD_REGIT_DATE
, TIME, COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS
, SELECTED_ID, SELECTED_DATE, BUYER_CODE, SELLER_CODE
FROM DETAIL_BUYLIST_VIEW
WHERE BUYER_ID = 'test2'
ORDER BY PD_REGIT_DATE DESC;

--> 구매정보 뷰에 BS_ID, BS_DATE 추가
CREATE OR REPLACE VIEW DETAIL_BUYLIST_VIEW
AS
SELECT PD_ID, PD_TITLE, PD_PRICE, SYSTEM, TO_CHAR(PD_REGIT_DATE, 'YYYY-MM-DD') AS PD_REGIT_DATE
    , TIME, TO_CHAR(COMP_DATE, 'YYYY-MM-DD') AS COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS
    , SE.SELECTED_ID, TO_CHAR(SE.SELECTED_DATE, 'YYYY-MM-DD') AS SELECTED_DATE, SE.BUYER_CODE, SE.SELLER_CODE
    , BS_ID, BS_DATE
FROM MY_PRODUCT_LIST MPL
LEFT OUTER JOIN SELECTED SE
ON MPL.BSE_ID = SE.SELECTED_ID
LEFT OUTER JOIN BID_SUCCESS BS
ON MPL.BSE_ID = BS.BS_ID;


SELECT PD_ID, PD_TITLE, PD_PRICE, SYSTEM, PD_REGIT_DATE
		, TIME, COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS
        , SELECTED_ID, SELECTED_DATE, BUYER_CODE, SELLER_CODE
        , BS_ID, BS_DATE
FROM DETAIL_BUYLIST_VIEW
WHERE BUYER_ID = 'test2'
ORDER BY PD_REGIT_DATE DESC;

SELECT *
FROM DELIVERY_PRODUCT;

SELECT *
FROM BID_LIST;

SELECT *
FROM BID_SUCCESS;

SELECT *
FROM DELI_COMPLETE_SELL;

SELECT *
FROM DELI_COMPLETE_BUY;

CREATE SEQUENCE BIDSEQ
NOCACHE;

INSERT INTO BID_LIST(BID_CODE, BID_PRICE, ADDRESS, ADDR_DETAIL, U_ID, DELI_PD_ID)
VALUES(CONCAT('bid_',BID_SEQ.NEXTVAL), 120000, '인천 중구 어딘가', '으슥한곳', 'test1', 'deli_11');

COMMIT;

CREATE SEQUENCE DELI_COMPLETE_SEQ
NOCACHE;


INSERT INTO DELI_COMPLETE_BUY(DELI_COMP_SELL_ID, PD_DELI_NUM, REVIEW, BS_ID)
VALUES(CONCAT('dcbuy_', DELI_COMPLETE_SEQ.NEXTVAL), '789715613', '감사요', 'bs_3');



SELECT PD_ID, PD_TITLE, NVL(PD_PRICE, -1) AS PD_PRICE, SYSTEM, PD_REGIT_DATE
, TIME, COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS
, SELECTED_ID, SELECTED_DATE, BUYER_CODE, SELLER_CODE
, BS_ID, BS_DATE
FROM
(
SELECT PD_ID, PD_TITLE, PD_PRICE, SYSTEM, PD_REGIT_DATE, TIME, COMP_DATE, SELLER_ID, BUYER_ID, ADDRESS, STATUS
, SELECTED_ID, SELECTED_DATE, BUYER_CODE, SELLER_CODE
, BS_ID, BS_DATE
, ROW_NUMBER() OVER(PARTITION BY PD_ID ORDER BY COMP_DATE ASC) AS RN
FROM DETAIL_BUYLIST_VIEW
WHERE SELLER_ID = 'test2'
ORDER BY PD_REGIT_DATE DESC
)
WHERE RN=1
;


SELECT *
FROM DIRE_COMPLETE_BUY;

SELECT *
FROM DELI_COMPLETE_BUY;

CREATE SEQUENCE DELI_COMPLETE_SELL_SEQ
NOCACHE;

INSERT INTO DELI_COMPLETE_SELL(DELI_COMP_SELL_ID, PD_DELI_NUM, REVIEW, BS_ID)
VALUES(CONCAT('dcsell_', DELI_COMPLETE_SELL_SEQ.NEXTVAL), 1515, '굿', 'bs_1');

ROLLBACK;
