
-- 구매확정 프로시저
CREATE OR REPLACE PROCEDURE DIREBUY_COMPLETE_PRC
( V_SID         IN SELECTED.SELECTED_ID%TYPE
, V_BUYER_CODE  IN SELECTED.BUYER_CODE%TYPE
, V_REVIEW      IN DIRE_COMPLETE_BUY.REVIEW%TYPE
)
IS
    C_BUYER_CODE        SELECTED.SELLER_CODE%TYPE;
    USER_DEFINE_ERROR   EXCEPTION;
    DISCODE_ERROR       EXCEPTION;
    COUNTOVER_ERROR     EXCEPTION;
    V_COUNT             NUMBER;
BEGIN
    SELECT SELLER_CODE INTO C_BUYER_CODE
    FROM SELECTED
    WHERE SELECTED_ID = V_SID;
    
    SELECT COUNT(*) INTO V_COUNT
    FROM DIRE_COMPLETE_BUY
    WHERE SELECTED_ID = V_SID;
    
    IF V_COUNT >= 1 THEN
        RAISE COUNTOVER_ERROR;
    END IF;
    
    IF C_BUYER_CODE = V_BUYER_CODE THEN
        INSERT INTO DIRE_COMPLETE_BUY(DIRE_COMP_BUY_ID, REVIEW, SELECTED_ID)
        VALUES(CONCAT('rcBuy_',DIRE_COMPLETE_BUY_SEQ.NEXTVAL), V_REVIEW, V_SID);
    ELSE
        RAISE DISCODE_ERROR;
    END IF;

    COMMIT;
    
    EXCEPTION
        WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20004, '에러 발생');
            ROLLBACK;
        WHEN DISCODE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20005, '코드가 다릅니다.');
        WHEN COUNTOVER_ERROR
            THEN RAISE_APPLICATION_ERROR(-20006, '이미 구매확정된 글입니다.');
        WHEN OTHERS
            THEN ROLLBACK;
END;
--==>> Procedure BUY_COMPLETE_PRC이(가) 컴파일되었습니다.

--==>> 805RLDYGTUWXABZF
EXEC DIREBUY_COMPLETE_PRC('sel_9', 'C0BKQGRZvhuyhpme', '감사합니다');
--==>> PL/SQL 프로시저가 성공적으로 완료되었습니다.

