SELECT USER
FROM DUAL;
--==>> COMFIT


SELECT *
FROM SUGGEST_LIST;
--==>> suggest_1	950000	2022-06-12	2022-06-10	서울 도봉구 우이천로 50길 40	우림슈퍼앞	test2	dire_1	1

-- ○ 구매제안 목록 조회 쿼리
-- 구매제안 코드 구매자 닉네임, 금액, 거래날짜, 장소+장소상세, 등록날짜
CREATE OR REPLACE VIEW SUGGEST_LIST_REALVIEW
AS
SELECT SL.SUGGEST_CODE, UI.U_NICKNAME, SL.SUGGEST_PRICE AS PRICE, SL.SUGGEST_TIME, SL.SUGGEST_PLACE
     , SL.PLACE_DETAIL, SL.SUGGEST_DATE, SL.DIRE_PD_ID
FROM SUGGEST_LIST SL JOIN COMFIT_USER CU
     ON SL.U_ID = CU.U_ID
        JOIN USER_INFORMATION UI
          ON CU.U_ID = UI.U_ID;
--==>> View SUGGEST_LIST_REALVIEW이(가) 생성되었습니다.

SELECT SUGGEST_CODE, U_NICKNAME, PRICE, SUGGEST_TIME AS SUGGEST_TIME, SUGGEST_PLACE, PLACE_DETAIL, SUGGEST_DATE
FROM SUGGEST_LIST_REALVIEW
WHERE DIRE_PD_ID = 'dire_1';



ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
--==>> Session이(가) 변경되었습니다.

        