SELECT USER
FROM DUAL;

select *
from delivery_product;

SELECT DELI_PD_ID, PD_NAME, 
FROM DELIVERY_PRODUCT;

select *
from all_views
where owner = 'COMFIT';

select *
from total_product_view;

SELECT *
FROM DIRE_PD_COUNT_VIEW;

SELECT DELI_PD_ID, PD_TITLE, PD_START_PRICE, BID_PRICE, PD_REGIT_DATE, BID_DATE, RANK
, (SELECT COMP_DATE
    FROM
    (
        SELECT BS_ID, COMP_DATE, RANK() OVER (PARTITION BY BS_ID ORDER BY COMP_DATE DESC) AS RANK
        FROM
        (
        SELECT DELI_COMP_SELL_ID AS COMP_ID ,  REVIEW, SELL_COMP_DATE AS COMP_DATE, BS_ID
        FROM DELI_COMPLETE_SELL
        UNION
        SELECT DELI_COMP_BUY_ID AS COMP_ID, REVIEW, BUY_COMP_DATE AS COMP_DATE, BS_ID
        FROM DELI_COMPLETE_BUY
        )
    )WHERE RANK = 1
    AND BS_ID = DPCV.BS_ID
    ) AS COMP_DATE
, SELLER_ID, BUYER_ID, IMD_PRICE, ADDRESS
,(CASE WHEN COMPLETECOUNT = 2 THEN '거래완료'
WHEN BUYCOUNT = 1 AND SELLCOUNT = 0 THEN '판매확정대기중'
WHEN SELLCOUNT = 1 AND BUYCOUNT = 0 THEN '구매확정대기중'
WHEN SUCCESSCOUNT = 1 AND COMPLETECOUNT = 0 THEN '거래중'
WHEN RANK != 1 THEN '다른입찰이낙찰'
WHEN PD_REGIT_DATE +4 < SYSDATE THEN '유찰됨'
WHEN BIDCOUNT > 0 THEN '입찰중'
WHEN BIDCOUNT = 0 THEN '입찰받는중' 
ELSE '에러' 
END) AS STATUS
FROM DELI_PD_COUNT_VIEW DPCV;




