SELECT *
FROM USER_INFORMATION;

COMMIT;

DELETE
FROM DIRECT_PRODUCT
WHERE DIRE_PD_ID = '';

DELETE
FROM DELIVERY_PRODUCT
WHERE DELI_PD_ID = '';

SELECT V.PD_ID AS PD_ID, V.PD_TITLE AS PD_TITLE, V.PRICE AS PRICE
     , V.DISTANCE AS DISTANCE, V.PD_PHOTO AS PD_PHOTO
FROM
	(
	SELECT PD_ID, PD_NAME, PRICE, PD_PHOTO, PD_TITLE
	     , ROUND(DISTANCE_WGS84(LAT, LON, #{lat}, #{lon}), 2) AS DISTANCE
	FROM DIRE_PD_NEAR_VIEW
	) V
ORDER BY V.DISTANCE;

-- ○ 처음에 5개 띄워줌 (무한스크롤 전)
SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND CATEGORY_NAME = '그래픽카드'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
)
WHERE RN <=15 ;

SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND CATEGORY_NAME = '그래픽카드'
	ORDER BY COMP_DATE DESC
	, STATUS DESC;
)
WHERE RN <=15 ;
COMMIT;
    
-- ○ 이후에 5개씩 계속 띄워줌
SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND CATEGORY_NAME = '그래픽카드'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
)
WHERE RN > 기존최대값 AND RN <= 기존최대값 + 5 ;

SELECT *
FROM SEQ;

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처21', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처22', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처23', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처24', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처25', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처26', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처27', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처28', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처29', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처30', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처31', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처32', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처33', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처34', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처35', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처36', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처37', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처38', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처39', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');

INSERT INTO DELIVERY_PRODUCT(DELI_PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_START_PRICE, PD_HITCOUNT, PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, U_ID, CF_PRICE, COMMENTS, IMD_PRICE)
VALUES ('deli_'||TO_CHAR(DELI_PD_SEQ.NEXTVAL), '그래픽카드급처11', 'gtx 1060', 'gtx 1060.jpg', '2024-02', '100000', '0', TO_DATE('2022-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'maker_16', '2', 'test2', '114000', 'ㅇㅇㅇ', '130000');



COMMIT;

-- 1번 : 일반검색
SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND PD_TITLE LIKE '%%'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
)
WHERE RN <= 20;

-- 일반검색하고 스크롤 내리면
SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND PD_TITLE LIKE '%그래픽%'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
)
WHERE RN > 0 AND RN <= 40;

-- 2번  : 고가순  
SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND PD_TITLE LIKE '%그래픽%'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
	, PD_PRICE DESC
)
WHERE RN <= 20;    
    
SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND PD_TITLE LIKE '%그래픽%'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
	, PD_PRICE DESC
)
WHERE RN > 20 AND RN <= 40;


    
    
-- 3번 : 저가순
SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND PD_TITLE LIKE '%노트북%'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
	, PD_PRICE ASC
)
WHERE RN <= 20;

-- 저가순 스크롤 내리면
SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND PD_TITLE LIKE '%노트북%'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
	, PD_PRICE ASC
)
WHERE RN > 20 AND RN <= 40;    
    
    
    
-- 4번 : 직거래전체    
SELECT  RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND PD_TITLE LIKE '%%'
	AND SYSTEM = '직거래(제안거래)'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
)
WHERE RN <= 20;    

-- 직거래 스크롤 요청하면
SELECT  RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND PD_TITLE LIKE '%%'
	AND SYSTEM = '직거래(제안거래)'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
)
WHERE RN > 20 AND RN <= 40;    



-- 5번 : 택배거래 전체
SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND PD_TITLE LIKE '%%'
	AND SYSTEM = '택배(경매)'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
)
WHERE RN <= 20;

-- 택배거래 스크롤 요청하면
SELECT RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM
(
SELECT ROWNUM AS RN, PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PRODUCT_LIST_VIEW2
	WHERE BLIND = 'NOT'
	AND PD_TITLE LIKE '%%'
	AND SYSTEM = '택배(경매)'
	ORDER BY COMP_DATE DESC
	, STATUS DESC
)
WHERE RN > 20 AND RN <= 40;


SELECT ROWNUM, PD_ID, PD_TITLE, PRICE, PD_REGIT_DATE, PD_PHOTO, PD_HOPE_EDATE
FROM
(
		SELECT ROWNUM AS RN, PD_ID, PD_TITLE, PRICE, PD_REGIT_DATE, PD_PHOTO
		     , CASE WHEN SYSDATE - PD_REGIT_DATE > 19 THEN 'X'
		       WHEN (PD_REGIT_DATE+5 < SYSDATE) THEN '1' 
		       ELSE '0'
		       END AS PD_HOPE_EDATE
		FROM DELI_PD_LIST_REALVIEW
		ORDER BY PD_HOPE_EDATE, RN DESC
)
WHERE ROWNUM <= 16;


