SELECT USER
FROM DUAL;

SELECT *
FROM USER_INFORMATION;

-- ○ 닉네임 체크용 조회쿼리
SELECT COUNT (*) COUNT
FROM USER_INFORMATION
WHERE U_NICKNAME = '이오'; 
--==>> 0

-- ○ 입찰등록데이터 조회
-- 입찰자닉네임, 입찰금액, 입찰일시, 배송지
SELECT *
FROM BID_LIST
WHERE DELI_PD_ID = 'deli_1';


CREATE OR REPLACE VIEW BID_LIST_REALVIEW
AS
SELECT BL.BID_CODE, UI.U_NICKNAME, BL.BID_PRICE AS PRICE, BL.BID_DATE, BL.ADDRESS, BL.DELI_PD_ID
FROM BID_LIST BL JOIN COMFIT_USER CU
     ON BL.U_ID = CU.U_ID
        JOIN USER_INFORMATION UI
          ON CU.U_ID = UI.U_ID;
--==>> View BID_LIST_REALVIEW이(가) 생성되었습니다.

/*
삭이오	155000	2022-06-10	서울특별시 마포구 월드컵북로 21          
*/

-- 입찰정보 조회 쿼리문
SELECT BID_CODE, U_NICKNAME, PRICE, BID_DATE, ADDRESS
FROM BID_LIST_REALVIEW
WHERE DELI_PD_ID = 'deli_1';

