
--> 카테고리 선택시 출력문
SELECT PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE
	, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
	FROM PD_LIST_VIEW
	WHERE CATEGORY_NAME = '그래픽카드'
    AND PD_TITLE LIKE '%팔아요%';

--> 신고랑 합쳐서 블라인드 걸러내기
CREATE OR REPLACE VIEW PRODUCT_LIST_VIEW2
AS
SELECT PLV.PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE
	, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
    , NVL(BLIND, 'NOT') AS BLIND
	FROM PD_LIST_VIEW PLV
LEFT OUTER JOIN PRODUCT_REPORT_VIEW PRV
ON PLV.PD_ID = PRV.PD_ID;


-- 검색리스트(블라인드 처리된 항목 제외)
SELECT PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM PRODUCT_LIST_VIEW2
WHERE BLIND = 'NOT'
AND PD_TITLE LIKE '%팔아요%'
ORDER BY COMP_DATE DESC
, STATUS DESC;

-- 검색 고가순
SELECT PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM PRODUCT_LIST_VIEW2
WHERE BLIND = 'NOT'
AND PD_TITLE LIKE '%팔아요%'
ORDER BY COMP_DATE DESC
, STATUS DESC
, PD_PRICE DESC;

-- 검색 저가순
SELECT PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM PRODUCT_LIST_VIEW2
WHERE BLIND = 'NOT'
AND PD_TITLE LIKE '%팔아요%'
ORDER BY COMP_DATE DESC
, STATUS DESC
, PD_PRICE ASC;

-- 검색 직거래만
SELECT PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM PRODUCT_LIST_VIEW2
WHERE BLIND = 'NOT'
AND PD_TITLE LIKE '%레오폴드%'
AND SYSTEM = '직거래(제안거래)'
ORDER BY COMP_DATE DESC
, STATUS DESC;

-- 검색 택배거래만
SELECT PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM PRODUCT_LIST_VIEW2
WHERE BLIND = 'NOT'
AND PD_TITLE LIKE '%팔아요%'
AND SYSTEM = '택배(경매)'
AND CATEGORY_NAME like '%그래픽카드%'
ORDER BY COMP_DATE DESC
, STATUS DESC;


-- 카테고리 선택
SELECT PD_ID, CATEGORY_NAME, PD_REGIT_DATE, U_ID, PD_TITLE, DEAL_TYPE, PD_PRICE, SYSTEM, COMP_DATE, SELLER_ID, BUYER_ID, STATUS, PD_PHOTO
FROM PRODUCT_LIST_VIEW2
WHERE BLIND = 'NOT'
AND CATEGORY_NAME = '그래픽카드'
ORDER BY COMP_DATE DESC
, STATUS DESC;

SELECT *
FROM ALL_USER_POINT_VIEW;

SELECT *
FROM PRODUCT_LIST_VIEW2;

SELECT *
FROM REP_HANDLE_CATEGORY;
--==>>
/*
1	신고자패널티
2	피신고자패널티
3	둘다패널티
4	둘다패널티없음
*/
