-- ■ 비밀번호 암호화 

SELECT USER 
FROM DUAL;
--==>> COMFIT

SELECT *
FROM USER_INFORMATION;
/*
issac1162@test.com	오이삭	인천광역시 중구 신흥동1가 6-4	1234	010-2988-1162	오이삭입니다.	삭이오	2022-06-10	test1
kkk@naver.com	김민성	서울특별시 중구 을지로 5가 223-4	1234	010-2222-3333	C:\Downloads	민성킴의활약	2022-06-11	test2
*/



-- 상품 1개 (상세페이지) 조회 쿼리
SELECT * 
FROM AD_PD_LIST_REALVIEW;

SELECT *
FROM DIRE_PRODUCT_VIEW;

ALTER TABLE DIRECT_PRODUCT
ADD  CF_PRICE NUMBER DEFAULT 0;
--==>> Table DIRECT_PRODUCT이(가) 변경되었습니다.

ALTER TABLE DELIVERY_PRODUCT
ADD   CF_PRICE NUMBER DEFAULT 0;
---==>> Table DELIVERY_PRODUCT이(가) 변경되었습니다.


COMMIT;

SELECT *
FROM DIRECT_PRODUCT;

-- ○직거래 상품 뷰
CREATE OR REPLACE VIEW DIRE_PD_LIST_REALVIEW
AS
SELECT DP.DIRE_PD_ID AS PD_ID, DP.PD_TITLE, DP.PD_NAME, DP.PD_PHOTO, DP.PD_AS_REMAIN, DP.PD_HITCOUNT
     , DP.PD_HOPEPRICE AS PRICE, DP.PD_HOPE_SDATE, DP.PD_HOPE_EDATE, DP.PD_HOPE_STIME, DP.PD_HOPE_ETIME
     , DP.PD_HOPE_PLACE, DP.PD_REGIT_DATE, DP.PD_MAKER_ID, DP.PD_AS_ID, PA.PD_AS_NAME, PC.CATEGORY_NAME
     , DP.U_ID AS SELLER, UI.U_NICKNAME, PM.MAKER_NAME, PM.MAKER_NAME2, DP.CF_PRICE, NVL(DP.COMMENTS, '특이사항 없음') AS COMMENTS
FROM DIRECT_PRODUCT DP JOIN PRODUCT_MAKER PM
     ON DP.PD_MAKER_ID = PM.PD_MAKER_ID 
        JOIN PRODUCT_CATEGORY PC
          ON PM.PD_CATEGORY_ID = PC.PD_CATEGORY_ID
             JOIN PRODUCT_AS PA
               ON DP.PD_AS_ID = PA.PD_AS_ID
                  JOIN COMFIT_USER CU
                    ON DP.U_ID = CU.U_ID
                       JOIN USER_INFORMATION UI
                         ON CU.U_ID = UI.U_ID;
--==>> View DIRE_PD_LIST_REALVIEW이(가) 생성되었습니다.


-- ○택배거래 상품 뷰
CREATE OR REPLACE VIEW DELI_PD_LIST_REALVIEW
AS
SELECT DP.DELI_PD_ID AS PD_ID, DP.PD_TITLE, DP.PD_NAME, DP.PD_PHOTO, DP.PD_AS_REMAIN, DP.PD_HITCOUNT
     , DP.PD_START_PRICE AS PRICE, DP.PD_REGIT_DATE, DP.PD_MAKER_ID, DP.PD_AS_ID, PA.PD_AS_NAME, PC.CATEGORY_NAME
     , DP.U_ID AS SELLER, UI.U_NICKNAME, PM.MAKER_NAME, PM.MAKER_NAME2, DP.CF_PRICE, NVL(DP.COMMENTS, '특이사항 없음') AS COMMENTS
     , NVL(DP.IMD_PRICE, 0) AS IMDPRICE
FROM DELIVERY_PRODUCT DP JOIN PRODUCT_MAKER PM
     ON DP.PD_MAKER_ID = PM.PD_MAKER_ID 
        JOIN PRODUCT_CATEGORY PC
          ON PM.PD_CATEGORY_ID = PC.PD_CATEGORY_ID
             JOIN PRODUCT_AS PA
               ON DP.PD_AS_ID = PA.PD_AS_ID
                  JOIN COMFIT_USER CU
                    ON DP.U_ID = CU.U_ID
                       JOIN USER_INFORMATION UI
                         ON CU.U_ID = UI.U_ID;


CREATE OR REPLACE VIEW PD_LIST_MAIN_VIEW
AS
SELECT PD_ID, PD_NAME, PRICE
FROM DELI_PD_LIST_REALVIEW
UNION ALL
SELECT PD_ID, PD_NAME, PRICE
FROM DIRE_PD_LIST_REALVIEW;
--==>> View PD_LIST_MAIN_VIEW이(가) 생성되었습니다.

SELECT PD_ID, PD_NAME, PRICE
FROM PD_LIST_MAIN_VIEW;
/*
deli_1	intel I-7 8700	150000
dire_1	GeForce RTX 3060 Ti	1000000
*/

-- ○ 클릭된 직거래 상품을 조회하는 쿼리문
SELECT PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_HITCOUNT, PRICE
     , TO_CHAR(TO_DATE(PD_HOPE_SDATE, 'YYYY-MM-DD')) AS PD_HOPE_SDATE, TO_CHAR(TO_DATE(PD_HOPE_EDATE, 'YYYY-MM-DD')) AS PD_HOPE_EDATE
     , PD_HOPE_STIME, PD_HOPE_ETIME, PD_HOPE_PLACE
     , PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, PD_AS_NAME, CATEGORY_NAME, SELLER
     , U_NICKNAME, MAKER_NAME, MAKER_NAME2, CF_PRICE, COMMENTS
FROM DIRE_PD_LIST_REALVIEW
WHERE PD_ID = 'dire_1';

SELECT SELLER
FROM DIRE_PD_LIST_REALVIEW;

-- ○ 택배거래 상품 조회 쿼리문
SELECT PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_HITCOUNT, PRICE
     , PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, PD_AS_NAME, CATEGORY_NAME, SELLER
     , U_NICKNAME, MAKER_NAME, MAKER_NAME2, CF_PRICE, COMMENTS, IMDPRICE
FROM DELI_PD_LIST_REALVIEW
WHERE PD_ID = 'deli_1';

ALTER TABLE DELIVERY_PRODUCT
ADD IMD_PRICE NUMBER;

COMMIT; 

SELECT *
FROM DELIVERY_PRODUCT;
COMMIT;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
