SELECT USER
FROM DUAL;
--=-=> COMFIT

SELECT *
FROM SUGGEST_LIST;

INSERT INTO SUGGEST_LIST(SUGGEST_CODE, SUGGEST_PRICE, SUGGEST_TIME
                       , SUGGEST_PLACE, PLACE_DETAIL, U_ID, DIRE_PD_ID)
VALUES(CONCAT('suggest_', TO_CHAR(SUGGEST_SEQ.NEXTVAL)), 855500, TO_DATE(CONCAT('2022-06-18', '16:30:00'), 'YYYY-MM-DD HH24:MI:SS')
              , '서울 도봉구 우이천로 39길 10', '우이성당 앞', 'test2', 'dire_2');
SELECT *
FROM SUGGEST_LIST;

SELECT *
FROM ALL_USER_POINT_VIEW;

CREATE OR REPLACE PROCEDURE ADD_SUGGEST
(
    V_PRICE IN SUGGEST_LIST.SUGGEST_PRICE%TYPE  -- 가격
  , V_HOPE_DATE IN VARCHAR2  -- 연월일
  , V_HOPE_TIME IN VARCHAR2  -- 시간  
  , V_HOPE_PLACE IN SUGGEST_LIST.SUGGEST_PLACE%TYPE -- 장소
  , V_PLACE_DETAIL IN SUGGEST_LIST.PLACE_DETAIL%TYPE -- 장소상세
  , V_U_ID  IN SUGGEST_LIST.U_ID%TYPE -- 사람코드
  , V_DIRE_PD_ID IN SUGGEST_LIST.DIRE_PD_ID%TYPE --  상품코드  
)
IS
    V_POINT            NUMBER := 0;
    USER_DEFINE_ERROR  EXCEPTION;
BEGIN
    
    SELECT U_POINT INTO V_POINT
    FROM ALL_USER_POINT_VIEW2
    WHERE U_ID = V_U_ID;
  
    IF V_POINT < V_PRICE
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    INSERT INTO SUGGEST_LIST(SUGGEST_CODE, SUGGEST_PRICE, SUGGEST_TIME
                       , SUGGEST_PLACE, PLACE_DETAIL, U_ID, DIRE_PD_ID)
    VALUES(CONCAT('suggest_', TO_CHAR(SUGGEST_SEQ.NEXTVAL+1)), V_PRICE
                , TO_DATE(CONCAT(V_HOPE_DATE, CONCAT(' ', V_HOPE_TIME)), 'YYYY-MM-DD HH24:MI:SS')
                , V_HOPE_PLACE, V_PLACE_DETAIL, V_U_ID, V_DIRE_PD_ID);

     -- 커밋

    -- 예외
    EXCEPTION
        WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20003, '인서트오류 발생');
            ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;     
END  ADD_SUGGEST;
--==>> Procedure ADD_SUGGEST이(가) 컴파일되었습니다.
COMMIT;

EXEC ADD_SUGGEST(90000, '2022-06-18', '16:00', '서울 도봉구 창동', '창동역2번출구 이마트앞', 'test1', 'dire_2');

SELECT *
FROM SEQ;


SHOW ERRORS;
ROLLBACK;
SELECT *
FROM SUGGEST_LIST
WHERE DIRE_PD_ID='dire_2';

SELECT U_POINT
FROM ALL_USER_POINT_VIEW2
WHERE U_ID = 'test2';

CREATE OR REPLACE VIEW ALL_USER_POINT_VIEW2
AS
SELECT U_ID, POINT AS U_POINT
FROM ALL_USER_POINT_VIEW;


INSERT INTO SUGGEST_LIST(SUGGEST_CODE, SUGGEST_PRICE, SUGGEST_TIME
                       , SUGGEST_PLACE, PLACE_DETAIL, U_ID, DIRE_PD_ID)
    VALUES(CONCAT('suggest_', TO_CHAR(SUGGEST_SEQ.NEXTVAL+1)), 855500, TO_DATE(CONCAT('2022-06-18', '16:30:00'), 'YYYY-MM-DD HH24:MI:SS')
                , '서울 도봉구 우이천로 39길 10', '우이성당 앞', 'test2', 'dire_2');

SELECT *
FROM TAB
WHERE TABTYPE='VIEW';


DESC SUGGEST_LIST;



SELECT PD_ID, PD_TITLE, PD_NAME, PD_PHOTO, PD_AS_REMAIN, PD_HITCOUNT, PRICE
		     , SUBSTR(TO_CHAR(PD_HOPE_SDATE), 1, 10) AS PD_HOPE_SDATE, SUBSTR(TO_CHAR(PD_HOPE_EDATE), 1, 10) AS PD_HOPE_EDATE
		     , PD_HOPE_STIME, PD_HOPE_ETIME, PD_HOPE_PLACE
		     , PD_REGIT_DATE, PD_MAKER_ID, PD_AS_ID, PD_AS_NAME, CATEGORY_NAME, SELLER
		     , U_NICKNAME, MAKER_NAME, MAKER_NAME2, CF_PRICE, COMMENTS
		     , PD_HOPE_EDATE + ROUND(TO_NUMBER(SUBSTR(PD_HOPE_ETIME, 1, 2)-4)/24, 10) AS REMAIN_DATE
		FROM DIRE_PD_LIST_REALVIEW
		WHERE PD_ID = 'dire_2';
        
SELECT *
FROM DIRE_PD_NEAR_VIEW;


