
SELECT *
FROM USER_INFORMATION U JOIN DELI_PD_BANNED DPB
ON U.U_ID = DPB.U_ID;


SELECT *
FROM DELIVERY_PD_REPORT;

SELECT *
FROM DELI_PD_REP_HANDLE;

SELECT *
FROM DELI_PD_BANNED;

SELECT *
FROM DELIVERY_PRODUCT;

INSERT INTO DELIVERY_PD_REPORT(REP_ID, REP_CONTENTS, U_ID, PD_REP_CID, DELI_PD_ID)
VALUES('delirep_1', '유해한 내용 업로드', 'test1', 3, 'deli_1');

INSERT INTO DELI_PD_REP_HANDLE(REP_ID, AD_ID, HAN_CATE_ID)
VALUES('delirep_1', 'cf_admin', 2);

INSERT INTO DELI_PD_BANNED(BAN_ID, BAN_REA_DETAIL, REP_ID, BAN_CATE_ID)
VALUES('ban_1', '유해한 내용을 업로드한 것을 확인함', 'delirep_1', 1);



-- 택배 상품 누적 차단 카운트를 위한 view
CREATE OR REPLACE VIEW DELIVERY_PD_BANNED_VIEW
AS
SELECT DPR.REP_ID, DPR.REP_CONTENTS, DPR.REP_DATE, DPR.PD_REP_CID, DPR.DELI_PD_ID
     , DPH.REP_HAN_DATE, DPH.HAN_CATE_ID
     , DPB.BAN_ID, DPB.BAN_REA_DETAIL, DPB.BAN_DATE, DPB.BAN_CATE_ID
     , DP.PD_TITLE, DP.PD_REGIT_DATE,DPR.U_ID AS REPORTER, DP.U_ID AS REPORTED , DPH.AD_ID
FROM DELIVERY_PD_REPORT DPR 
    JOIN DELI_PD_REP_HANDLE DPH 
    ON DPR.REP_ID = DPH.REP_ID 
    JOIN DELI_PD_BANNED DPB
    ON DPH.REP_ID = DPB.REP_ID
    JOIN DELIVERY_PRODUCT DP
    ON DP.DELI_PD_ID = DPR.DELI_PD_ID;


-- 택배 상품 누적 차단 횟수 확인 쿼리문
SELECT COUNT(*) AS COUNT
FROM DELIVERY_PD_BANNED_VIEW
WHERE REPORTED = 'test2';


-- 직거래 상품 누적 차단 카운트를 위한 view
CREATE OR REPLACE VIEW DIRECT_PD_BANNED_VIEW
AS
SELECT DPR.REP_ID, DPR.REP_CONTENTS, DPR.REP_DATE, DPR.PD_REP_CID, DPR.DIRE_PD_ID
     , DPH.REP_HAN_DATE, DPH.HAN_CATE_ID
     , DPB.BAN_ID, DPB.BAN_REA_DETAIL, DPB.BAN_DATE, DPB.BAN_CATE_ID
     , DP.PD_TITLE, DP.PD_REGIT_DATE,DPR.U_ID AS REPORTER, DP.U_ID AS REPORTED , DPH.AD_ID
FROM DIRECT_PD_REPORT DPR 
    JOIN DIRE_PD_REP_HANDLE DPH 
    ON DPR.REP_ID = DPH.REP_ID 
    JOIN DIRE_PD_BANNED DPB
    ON DPH.REP_ID = DPB.REP_ID
    JOIN DIRECT_PRODUCT DP
    ON DP.DIRE_PD_ID = DPR.DIRE_PD_ID;


-- 직거래 상품 누적 차단 횟수 확인 쿼리문
SELECT COUNT(*) AS COUNT
FROM DIRECT_PD_BANNED_VIEW
WHERE REPORTED = 'test2';



-- 택배 거래 누적 차단 카운트를 위한 view
CREATE OR REPLACE VIEW DELIVERY_TRANS_BANNED_VIEW
AS
SELECT DTB.BAN_ID, DTB.BAN_REA_DETAIL, DTB.BAN_DATE, DTB.REP_ID, DTB.BAN_CATE_ID
     , DTH.REP_HAN_DATE, DTH.HAN_CATE_ID
     , DTR.REP_CONTENTS, DTR.REP_DATE, DTR.TRANS_REP_CID, DTR.BS_ID, DTR.REPORTER_ID
     , BS.BS_DATE, BS.BID_CODE
     , BL.BID_DATE, DP.PD_TITLE, DP.PD_REGIT_DATE
     , CASE WHEN DTR.REPORTER_ID = 1 
        THEN BL.U_ID
        ELSE DP.U_ID
        END AS REPORTER
     , CASE WHEN DTR.REPORTER_ID = 1
        THEN DP.U_ID
        ELSE BL.U_ID
        END AS REPORTED
     , DTH.AD_ID 
FROM DELI_TA_BANNED DTB
    JOIN DELI_TA_REP_HANDLE DTH
    ON DTB.REP_ID = DTH.REP_ID
    JOIN DELIVERY_TA_REPORT DTR
    ON DTH.REP_ID = DTR.REP_ID
    JOIN BID_SUCCESS BS
    ON DTR.BS_ID = BS.BS_ID
    JOIN BID_LIST BL
    ON BS.BID_CODE = BL.BID_CODE
    JOIN DELIVERY_PRODUCT DP
    ON BL.DELI_PD_ID = DP.DELI_PD_ID;
--==>> View DELIVERY_TRANS_BANNED_VIEW이(가) 생성되었습니다.



-- 택배 거래 누적 차단 횟수 확인 쿼리문
SELECT COUNT(*) AS COUNT
FROM DILIVERY_TRANS_BANNED_VIEW
WHERE REPORTED = 'test2';



-- 직거래 거래 누적 차단 카운트를 위한 view
CREATE OR REPLACE VIEW DIRECT_TRANS_BANNED_VIEW
AS
SELECT DTB.BAN_ID, DTB.BAN_REA_DETAIL, DTB.BAN_DATE, DTB.REP_ID, DTB.BAN_CATE_ID
     , DTH.REP_HAN_DATE, DTH.HAN_CATE_ID
     , DTR.REP_CONTENTS, DTR.REP_DATE, DTR.TRANS_REP_CID, DTR.SELECTED_ID, DTR.REPORTER_ID
     , S.SELECTED_DATE, S.SUGGEST_CODE
     , SL.SUGGEST_DATE, DP.PD_TITLE, DP.PD_REGIT_DATE
     , CASE WHEN DTR.REPORTER_ID = 1 
        THEN SL.U_ID
        ELSE DP.U_ID
        END AS REPORTER
     , CASE WHEN DTR.REPORTER_ID = 1
        THEN DP.U_ID
        ELSE SL.U_ID
        END AS REPORTED
     , DTH.AD_ID 
FROM DIRE_TA_BANNED DTB
    JOIN DIRE_TA_REP_HANDLE DTH
    ON DTB.REP_ID = DTH.REP_ID
    JOIN DIRECT_TA_REPORT DTR
    ON DTH.REP_ID = DTR.REP_ID
    JOIN SELECTED S
    ON DTR.SELECTED_ID = S.SELECTED_ID
    JOIN SUGGEST_LIST SL
    ON S.SUGGEST_CODE = SL.SUGGEST_CODE
    JOIN DIRECT_PRODUCT DP
    ON SL.DIRE_PD_ID = DP.DIRE_PD_ID;
--==>> View DIRECT_TRANS_BANNED_VIEW이(가) 생성되었습니다.

-- 직거래 누적 차단 횟수 확인 쿼리문
SELECT COUNT(*) AS COUNT
FROM DIRECT_TRANS_BANNED_VIEW
WHERE REPORTED = 'test2';


-- 누적차단횟수 조회 쿼리문
SELECT COUNT(*) AS COUNT
FROM
(
SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
FROM DIRECT_TRANS_BANNED_VIEW
UNION
SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
FROM DELIVERY_TRANS_BANNED_VIEW
UNION
SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
FROM DIRECT_PD_BANNED_VIEW
UNION
SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
FROM DELIVERY_PD_BANNED_VIEW
)
WHERE REPORTED = 'test2';

SELECT U_EMAIL, U_NAME, U_NICKNAME, U_TEL, U_JOINDATE
FROM USER_INFORMATION;

SELECT *
FROM COMFIT_USER;

-- 관리자 화면에 띄울 유저 리스트
SELECT U_ID, U_EMAIL, U_NAME, U_NICKNAME, U_TEL, U_JOINDATE, 
(
    SELECT COUNT(*) AS COUNT
    FROM
    (
    SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
    FROM DIRECT_TRANS_BANNED_VIEW
    UNION
    SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
    FROM DELIVERY_TRANS_BANNED_VIEW
    UNION
    SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
    FROM DIRECT_PD_BANNED_VIEW
    UNION
    SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
    FROM DELIVERY_PD_BANNED_VIEW
    )
    WHERE U_ID = REPORTED
) AS BANCOUNT
FROM USER_INFORMATION;

-- 관리자 화면에 띄울 유저 리스트(페이징 처리)
SELECT ROWNUM, A.*
FROM(
        SELECT U_ID, U_EMAIL, U_NAME, U_NICKNAME, U_TEL, U_JOINDATE, 
        (
            SELECT COUNT(*) AS COUNT
            FROM
            (
            SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
            FROM DIRECT_TRANS_BANNED_VIEW
            UNION
            SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
            FROM DELIVERY_TRANS_BANNED_VIEW
            UNION
            SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
            FROM DIRECT_PD_BANNED_VIEW
            UNION
            SELECT BAN_ID, BAN_DATE, REPORTED, REPORTER
            FROM DELIVERY_PD_BANNED_VIEW
        )
        WHERE U_ID = REPORTED
    ) AS BANCOUNT
    FROM USER_INFORMATION
    ORDER BY U_ID
) A;

-- 총 인원 수
SELECT COUNT(*)
FROM USER_INFORMATION;


SELECT *
FROM DIRECT_TRANS_BANNED_VIEW;

-- 차단중인 회원을 보기 위한 view 1(택배거래 거래차단)
CREATE OR REPLACE VIEW DELIVERY_PD_USER_BANNED_VIEW
AS
SELECT REPORTED AS U_ID, U_EMAIL, U_NICKNAME, BAN_CATE_NAME, BAN_DATE
,BAN_DATE + TO_NUMBER(REPLACE(BAN_CATE_NAME,'일차단')) AS BAN_END_DATE, TRC.REP_CATE_NAME, BAN_REA_DETAIL
FROM DELIVERY_TRANS_BANNED_VIEW DV
JOIN USER_INFORMATION UI
ON DV.REPORTED = UI.U_ID
JOIN BAN_CATEGORY BC
ON DV.BAN_CATE_ID = BC.BAN_CATE_ID
JOIN TRANS_REP_CATEGORY TRC
ON DV.TRANS_REP_CID = TRC.TRANS_REP_CID;

-- 차단중인 회원을 보기 위한 view 2(직거래 거래차단)
CREATE OR REPLACE VIEW DIRECT_PD_USER_BANNED_VIEW
AS
SELECT REPORTED AS U_ID, U_EMAIL, U_NICKNAME, BAN_CATE_NAME, BAN_DATE
,BAN_DATE + TO_NUMBER(REPLACE(BAN_CATE_NAME,'일차단')) AS BAN_END_DATE, TRC.REP_CATE_NAME, BAN_REA_DETAIL
FROM DIRECT_TRANS_BANNED_VIEW DV
JOIN USER_INFORMATION UI
ON DV.REPORTED = UI.U_ID
JOIN BAN_CATEGORY BC
ON DV.BAN_CATE_ID = BC.BAN_CATE_ID
JOIN TRANS_REP_CATEGORY TRC
ON DV.TRANS_REP_CID = TRC.TRANS_REP_CID;

-- 차단중인 회원을 보기 위한 view 3(택배거래 상품차단)
CREATE OR REPLACE VIEW DELI_TRANS_USER_BANNED_VIEW
AS
SELECT REPORTED AS U_ID, U_EMAIL, U_NICKNAME, BAN_CATE_NAME, BAN_DATE
,BAN_DATE + TO_NUMBER(REPLACE(BAN_CATE_NAME,'일차단')) AS BAN_END_DATE, PC.REP_CATE_NAME, BAN_REA_DETAIL
FROM DELIVERY_PD_BANNED_VIEW DV
JOIN USER_INFORMATION UI
ON DV.REPORTED = UI.U_ID
JOIN BAN_CATEGORY BC
ON DV.BAN_CATE_ID = BC.BAN_CATE_ID
JOIN PD_REP_CATEGORY PC
ON DV.PD_REP_CID = PC.PD_REP_CID;

-- 차단중인 회원을 보기 위한 view 4(직거래 상품차단)
CREATE OR REPLACE VIEW DIRECT_TRANS_USER_BANNED_VIEW
AS
SELECT REPORTED AS U_ID, U_EMAIL, U_NICKNAME, BAN_CATE_NAME, BAN_DATE
,BAN_DATE + TO_NUMBER(REPLACE(BAN_CATE_NAME,'일차단')) AS BAN_END_DATE, PC.REP_CATE_NAME, BAN_REA_DETAIL
FROM DIRECT_PD_BANNED_VIEW DV
JOIN USER_INFORMATION UI
ON DV.REPORTED = UI.U_ID
JOIN BAN_CATEGORY BC
ON DV.BAN_CATE_ID = BC.BAN_CATE_ID
JOIN PD_REP_CATEGORY PC
ON DV.PD_REP_CID = PC.PD_REP_CID;


-- 현재 차단중인 회원 리스트 VIEW
CREATE OR REPLACE VIEW BANNED_USER_VIEW
AS
SELECT *
FROM
(
SELECT U_ID, U_EMAIL, U_NICKNAME, BAN_CATE_NAME, BAN_DATE, BAN_END_DATE, REP_CATE_NAME, BAN_REA_DETAIL
FROM DELIVERY_PD_USER_BANNED_VIEW
UNION
SELECT U_ID, U_EMAIL, U_NICKNAME, BAN_CATE_NAME, BAN_DATE, BAN_END_DATE, REP_CATE_NAME, BAN_REA_DETAIL
FROM DIRECT_PD_USER_BANNED_VIEW
UNION
SELECT U_ID, U_EMAIL, U_NICKNAME, BAN_CATE_NAME, BAN_DATE, BAN_END_DATE, REP_CATE_NAME, BAN_REA_DETAIL
FROM DELI_TRANS_USER_BANNED_VIEW
UNION
SELECT U_ID, U_EMAIL, U_NICKNAME, BAN_CATE_NAME, BAN_DATE, BAN_END_DATE, REP_CATE_NAME, BAN_REA_DETAIL
FROM DIRECT_TRANS_USER_BANNED_VIEW
)
WHERE BAN_DATE < SYSDATE 
AND BAN_END_DATE > SYSDATE;


--==>> (현재) 차단중인 회원 리스트
SELECT U_ID, U_EMAIL, U_NICKNAME, BAN_CATE_NAME, BAN_DATE, BAN_END_DATE, REP_CATE_NAME, BAN_REA_DETAIL
FROM BANNED_USER_VIEW;


COMMIT;


